/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["getIndex"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["getHealth"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/search/companies/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search companies
     * @description Fuzzy search companies by name, domain, or industry. Filter by industry, location, or size.
     */
    get: operations["getSearchCompanies"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/search/people/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search people
     * @description Fuzzy search people by name, job title, or LinkedIn username. Filter by industry, location, job title, company, or domain.
     */
    get: operations["getSearchPeople"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/import/preview": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Preview CSV import
     * @description Preview column mapping and sample data before importing.
     */
    post: operations["postImportPreview"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/import/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start CSV import
     * @description Upload a CSV file to start importing company and people data. Returns an import ID to track progress. The import is durable and will resume if the server restarts.
     */
    post: operations["postImport"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/import/list": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List all imports
     * @description Get a list of all import workflows with optional filtering by status.
     */
    get: operations["getImportList"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/import/{importId}/status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get import status
     * @description Check the status of an ongoing or completed import by its ID.
     */
    get: operations["getImportByImportIdStatus"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/import/sync": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Synchronous CSV import (legacy)
     * @description Upload a CSV file and wait for import to complete. Not recommended for large files. Use POST /import for durable async imports.
     */
    post: operations["postImportSync"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/populate-db/companies": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start company populate jobs
     * @description Start async jobs to populate the database with companies from multiple sources (CodeCrafter and HunterIO). Returns job IDs for polling.
     */
    post: operations["postPopulate-dbCompanies"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/populate-db/people": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start people populate job
     * @description Start an async job to populate the database with people matching the given filters. Returns a job ID for polling.
     */
    post: operations["postPopulate-dbPeople"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/populate-db/{jobId}/status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get populate job status
     * @description Get the status, progress, and results of a populate job. Poll this endpoint to check job completion.
     */
    get: operations["getPopulate-dbByJobIdStatus"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/populate-db/list": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List populate jobs
     * @description List all populate jobs with optional filtering by status.
     */
    get: operations["getPopulate-dbList"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getIndex: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: never
  }
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: never
  }
  getSearchCompanies: {
    parameters: {
      query?: {
        q?: string
        limit?: string
        industry?: string
        country?: string
        location?: string
        size?: string
        companyType?: string
        domain?: string
        website?: string
        linkedinUrl?: string
        facebookUrl?: string
        twitterUrl?: string
        foundedYear?: string
        locationContinent?: string
        locationPostalCode?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json":
            | {
                results: {
                  id: string
                  createdAt: string
                  updatedAt: string
                  name: string
                  domain: string
                  description: (string | null) | null
                  companyType: (string | null) | null
                  industry: (string | null) | null
                  size: (string | null) | null
                  website: (string | null) | null
                  genericEmails: string[]
                  foundedYear: (number | null) | null
                  linkedinUrl: (string | null) | null
                  facebookUrl: (string | null) | null
                  twitterUrl: (string | null) | null
                  locationName: (string | null) | null
                  locationLocality: (string | null) | null
                  locationMetro: (string | null) | null
                  locationRegion: (string | null) | null
                  locationGeo: (string | null) | null
                  locationStreetAddress: (string | null) | null
                  locationAddressLine2: (string | null) | null
                  locationPostalCode: (string | null) | null
                  locationCountry: (string | null) | null
                  locationContinent: (string | null) | null
                  additionalInfo: (unknown | null) | null
                  score: number
                }[]
                query: (string | null) | null
                filters: {
                  industry: (string | null) | null
                  country: (string | null) | null
                  location: (string | null) | null
                  size: (string | null) | null
                  companyType: (string | null) | null
                  domain: (string | null) | null
                  website: (string | null) | null
                  linkedinUrl: (string | null) | null
                  facebookUrl: (string | null) | null
                  twitterUrl: (string | null) | null
                  foundedYear: (number | null) | null
                  locationContinent: (string | null) | null
                  locationPostalCode: (string | null) | null
                }
              }
            | {
                results: unknown[]
                total: number
              }
        }
      }
    }
  }
  getSearchPeople: {
    parameters: {
      query?: {
        q?: string
        limit?: string
        industry?: string
        country?: string
        location?: string
        jobTitle?: string
        company?: string
        domain?: string
        email?: string
        skills?: string
        minExperience?: string
        maxExperience?: string
        subRole?: string
        companySize?: string
        companyType?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json":
            | {
                results: {
                  id: string
                  fullName: (string | null) | null
                  firstName: (string | null) | null
                  lastName: (string | null) | null
                  jobTitle: (string | null) | null
                  subRole: (string | null) | null
                  workEmail: (string | null) | null
                  personalEmail: (string | null) | null
                  mobile: (string | null) | null
                  phoneNumbers: (string | null) | null
                  location: (string | null) | null
                  locality: (string | null) | null
                  region: (string | null) | null
                  locationCountry: (string | null) | null
                  linkedinUrl: (string | null) | null
                  linkedinUsername: (string | null) | null
                  twitterUsername: (string | null) | null
                  githubUsername: (string | null) | null
                  companyDomain: (string | null) | null
                  companyName: (string | null) | null
                  companyIndustry: (string | null) | null
                  middleName: (string | null) | null
                  industry: (string | null) | null
                  skills: (string | null) | null
                  summary: (string | null) | null
                  yearsExperience: (string | null) | null
                  inferredSalary: (string | null) | null
                  facebookUrl: (string | null) | null
                  facebookUsername: (string | null) | null
                  score: number
                }[]
                query: (string | null) | null
                filters: {
                  industry: (string | null) | null
                  country: (string | null) | null
                  location: (string | null) | null
                  jobTitle: (string | null) | null
                  company: (string | null) | null
                  domain: (string | null) | null
                  email: (string | null) | null
                  skills: (string | null) | null
                  minExperience: (string | null) | null
                  maxExperience: (string | null) | null
                  subRole: (string | null) | null
                  companySize: (string | null) | null
                  companyType: (string | null) | null
                }
              }
            | {
                results: unknown[]
                total: number
              }
        }
      }
    }
  }
  postImportPreview: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @default File
           */
          file: string
        }
      }
    }
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            headers: string[]
            sampleRows: {
              [key: string]: string
            }[]
            mapping: {
              companyFields: {
                [key: string]: string
              }
              personFields: {
                [key: string]: string
              }
              unmapped: string[]
            }
            validation: {
              hasDomain: boolean
              hasEmail: boolean
              hasCompanyName: boolean
              hasPersonName: boolean
            }
          }
        }
      }
    }
  }
  postImport: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @default File
           */
          file: string
        }
      }
    }
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            importId: string
            /** @constant */
            status: "started"
            message: string
            statusUrl: string
          }
        }
      }
    }
  }
  getImportList: {
    parameters: {
      query?: {
        status?: "PENDING" | "SUCCESS" | "ERROR"
        limit?: string
        offset?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            importId: string
            /** @enum {string} */
            status: "PENDING" | "SUCCESS" | "ERROR" | "CANCELLED" | "RETRIES_EXCEEDED" | "NOT_FOUND"
            createdAt: string | null
          }[]
        }
      }
    }
  }
  getImportByImportIdStatus: {
    parameters: {
      query?: never
      header?: never
      path: {
        importId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            importId: string
            /** @enum {string} */
            status: "PENDING" | "SUCCESS" | "ERROR" | "CANCELLED" | "RETRIES_EXCEEDED" | "NOT_FOUND"
            progress: {
              processed: number
              total: number
              percent: number
            } | null
            result: {
              success: boolean
              totalRows: number
              companiesCreated: number
              companiesUpdated: number
              peopleCreated: number
              peopleUpdated: number
              errors: {
                row: number
                field?: string
                message: string
              }[]
              processingTimeMs: number
            } | null
            error: string | null
          }
        }
      }
    }
  }
  postImportSync: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @default File
           */
          file: string
        }
      }
    }
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            success: boolean
            summary: {
              totalRows: number
              companiesCreated: number
              companiesUpdated: number
              peopleCreated: number
              peopleUpdated: number
              errorsCount: number
            }
            columnMapping: {
              companyFields: {
                [key: string]: string
              }
              personFields: {
                [key: string]: string
              }
              unmapped: string[]
            }
            errors: {
              row: number
              field?: string
              message: string
            }[]
            processingTimeMs: number
          }
        }
      }
    }
  }
  "postPopulate-dbCompanies": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          q?: string
          /** @default 100 */
          limit?: number
          industry?: string
          country?: string
          location?: string
          size?: string
          companyType?: string
          domain?: string
          website?: string
          linkedinUrl?: string
          facebookUrl?: string
          twitterUrl?: string
          foundedYear?: number
          locationContinent?: string
          locationPostalCode?: string
        }
        "application/x-www-form-urlencoded": {
          q?: string
          /** @default 100 */
          limit?: number
          industry?: string
          country?: string
          location?: string
          size?: string
          companyType?: string
          domain?: string
          website?: string
          linkedinUrl?: string
          facebookUrl?: string
          twitterUrl?: string
          foundedYear?: number
          locationContinent?: string
          locationPostalCode?: string
        }
        "multipart/form-data": {
          q?: string
          /** @default 100 */
          limit?: number
          industry?: string
          country?: string
          location?: string
          size?: string
          companyType?: string
          domain?: string
          website?: string
          linkedinUrl?: string
          facebookUrl?: string
          twitterUrl?: string
          foundedYear?: number
          locationContinent?: string
          locationPostalCode?: string
        }
      }
    }
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            jobs: {
              /** @enum {string} */
              source: "codecrafter" | "hunterio"
              jobId: string
              /** @enum {string} */
              status: "started" | "already_running" | "completed" | "skipped"
              message: string
              statusUrl: string
            }[]
            message: string
          }
        }
      }
    }
  }
  "postPopulate-dbPeople": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": {
          q?: string
          /** @default 100 */
          limit?: number
          industry?: string
          country?: string
          location?: string
          jobTitle?: string
          company?: string
          domain?: string
          email?: string
          skills?: string
          minExperience?: number
          maxExperience?: number
          subRole?: string
          companySize?: string
          companyType?: string
        }
        "application/x-www-form-urlencoded": {
          q?: string
          /** @default 100 */
          limit?: number
          industry?: string
          country?: string
          location?: string
          jobTitle?: string
          company?: string
          domain?: string
          email?: string
          skills?: string
          minExperience?: number
          maxExperience?: number
          subRole?: string
          companySize?: string
          companyType?: string
        }
        "multipart/form-data": {
          q?: string
          /** @default 100 */
          limit?: number
          industry?: string
          country?: string
          location?: string
          jobTitle?: string
          company?: string
          domain?: string
          email?: string
          skills?: string
          minExperience?: number
          maxExperience?: number
          subRole?: string
          companySize?: string
          companyType?: string
        }
      }
    }
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            jobId: string
            /** @enum {string} */
            status: "started" | "already_running" | "completed"
            message: string
            statusUrl: string
          }
        }
      }
    }
  }
  "getPopulate-dbByJobIdStatus": {
    parameters: {
      query?: never
      header?: never
      path: {
        jobId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            jobId: string
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed" | "not_found"
            progress:
              | ({
                  phase: "starting" | "searching" | "normalizing" | "persisting" | "completed"
                  processed: number
                  total: number
                  percent: number
                } | null)
              | null
            result:
              | (
                  | (
                      | {
                          companiesCreated: number
                          companiesUpdated: number
                          totalProcessed: number
                          processingTimeMs: number
                          errors: {
                            message: string
                            domain?: string
                          }[]
                        }
                      | {
                          peopleCreated: number
                          peopleUpdated: number
                          totalProcessed: number
                          processingTimeMs: number
                          errors: {
                            message: string
                            email?: string
                          }[]
                        }
                    )
                  | null
                )
              | null
            error: (string | null) | null
          }
        }
      }
    }
  }
  "getPopulate-dbList": {
    parameters: {
      query?: {
        limit?: string
        offset?: string
        status?: "pending" | "running" | "completed" | "failed"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            jobs: {
              jobId: string
              /** @enum {string} */
              type: "company" | "people"
              /** @enum {string} */
              status: "pending" | "running" | "completed" | "failed" | "not_found"
              createdAt: string
              updatedAt: string
            }[]
            total: number
          }
        }
      }
    }
  }
}
