services:
  nextjs-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nextjs-sendgrid-webhook
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    restart: unless-stopped