// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ReviewStatusEnum string

const (
	ReviewStatusEnumPending          ReviewStatusEnum = "pending"
	ReviewStatusEnumExternalReview   ReviewStatusEnum = "external_review"
	ReviewStatusEnumInternalReview   ReviewStatusEnum = "internal_review"
	ReviewStatusEnumApproved         ReviewStatusEnum = "approved"
	ReviewStatusEnumRejected         ReviewStatusEnum = "rejected"
	ReviewStatusEnumRevisionRequired ReviewStatusEnum = "revision_required"
)

func (e *ReviewStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatusEnum(s)
	case string:
		*e = ReviewStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatusEnum: %T", src)
	}
	return nil
}

type NullReviewStatusEnum struct {
	ReviewStatusEnum ReviewStatusEnum `json:"review_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if ReviewStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatusEnum), nil
}

type UserRoleEnum string

const (
	UserRoleEnumAdmin            UserRoleEnum = "admin"
	UserRoleEnumUser             UserRoleEnum = "user"
	UserRoleEnumInternalReviewer UserRoleEnum = "internal_reviewer"
	UserRoleEnumExternalReviewer UserRoleEnum = "external_reviewer"
)

func (e *UserRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoleEnum(s)
	case string:
		*e = UserRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoleEnum: %T", src)
	}
	return nil
}

type NullUserRoleEnum struct {
	UserRoleEnum UserRoleEnum `json:"user_role_enum"`
	Valid        bool         `json:"valid"` // Valid is true if UserRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoleEnum), nil
}

// Organization departments for user categorization
type Department struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

// Available languages for translation and review
type Language struct {
	ID         uuid.UUID      `json:"id"`
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	NativeName sql.NullString `json:"native_name"`
	IsActive   sql.NullBool   `json:"is_active"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

// Review-related notifications for users
type ReviewNotification struct {
	ID               uuid.UUID    `json:"id"`
	UserID           uuid.UUID    `json:"user_id"`
	TranslationID    uuid.UUID    `json:"translation_id"`
	NotificationType string       `json:"notification_type"`
	Message          string       `json:"message"`
	IsRead           sql.NullBool `json:"is_read"`
	CreatedAt        sql.NullTime `json:"created_at"`
}

// Core translation data without review information
type TranslationDatum struct {
	ID                     uuid.UUID             `json:"id"`
	SourceText             string                `json:"source_text"`
	TargetLanguage         string                `json:"target_language"`
	TranslatedText         string                `json:"translated_text"`
	TranslationEngine      sql.NullString        `json:"translation_engine"`
	RedisKey               sql.NullString        `json:"redis_key"`
	ElementContext         pqtype.NullRawMessage `json:"element_context"`
	QualityConfidenceScore sql.NullInt32         `json:"quality_confidence_score"`
	CreatedBy              uuid.NullUUID         `json:"created_by"`
	CreatedAt              sql.NullTime          `json:"created_at"`
	UpdatedAt              sql.NullTime          `json:"updated_at"`
}

// Translation review workflow data
type TranslationReview struct {
	ID            uuid.UUID `json:"id"`
	TranslationID uuid.UUID `json:"translation_id"`
	// Current status in the review workflow
	ReviewStatus       NullReviewStatusEnum `json:"review_status"`
	CurrentReviewer    uuid.NullUUID        `json:"current_reviewer"`
	ExternalReviewerID uuid.NullUUID        `json:"external_reviewer_id"`
	InternalReviewerID uuid.NullUUID        `json:"internal_reviewer_id"`
	ExternalReviewedAt sql.NullTime         `json:"external_reviewed_at"`
	InternalReviewedAt sql.NullTime         `json:"internal_reviewed_at"`
	FinalApprovedAt    sql.NullTime         `json:"final_approved_at"`
	RejectionReason    sql.NullString       `json:"rejection_reason"`
	// Review queue priority (1=very low, 2=low, 3=normal, 4=high, 5=very high)
	Priority  sql.NullInt32 `json:"priority"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

// Complete audit trail of translation reviews
type TranslationReviewHistory struct {
	ID            uuid.UUID        `json:"id"`
	TranslationID uuid.UUID        `json:"translation_id"`
	ReviewerID    uuid.UUID        `json:"reviewer_id"`
	ReviewStage   string           `json:"review_stage"`
	Status        ReviewStatusEnum `json:"status"`
	Comments      sql.NullString   `json:"comments"`
	ReviewedAt    sql.NullTime     `json:"reviewed_at"`
	OriginalText  sql.NullString   `json:"original_text"`
	RevisedText   sql.NullString   `json:"revised_text"`
}

// System users with role-based access
type User struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	UserRole     UserRoleEnum   `json:"user_role"`
	IsActive     bool           `json:"is_active"`
	DepartmentID uuid.UUID      `json:"department_id"`
	EmployeeID   string         `json:"employee_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	LastLoginAt  sql.NullTime   `json:"last_login_at"`
}

// User permissions for editing specific languages
type UserEditLanguage struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	LanguageID uuid.UUID    `json:"language_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

// User permissions for reviewing specific languages
type UserReviewLanguage struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	LanguageID uuid.UUID    `json:"language_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
}
