import { ArrowRight, CheckCircle2, Eye, Loader2, Mail, Sparkles } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import { useTranslation } from "react-i18next"
import { useSearchParams } from "react-router-dom"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Progress } from "@/components/ui/progress"
import { useEmails } from "@/lib/api/hooks/emails"
import { useOnboardingProgress } from "@/lib/api/hooks/onboarding"
import { useUserWorkspaces } from "@/lib/api/hooks/workspaces"

// Polling interval for checking generation status (5 seconds)
const POLL_INTERVAL_MS = 5000

export function StepEmailGeneration() {
  const { t, i18n } = useTranslation()
  const [, setSearchParams] = useSearchParams()
  const [showFullEmail, setShowFullEmail] = useState(false)

  // Get user's workspace
  const currentUser = useMemo(() => JSON.parse(localStorage.getItem("user") || "{}"), [])
  const userId = currentUser?.id || ""
  const { data: userWorkspaces } = useUserWorkspaces(userId, !!userId)
  const workspace = userWorkspaces?.[0]
  const isKorean = i18n.language === "ko"

  // Fetch emails from DB - these are the preview emails generated by autoGenerateOnboarding
  const {
    data: emailsData,
    isLoading: isLoadingEmails,
    refetch: refetchEmails,
  } = useEmails({
    workspaceId: workspace?.id || "",
    limit: 50,
  })

  // Onboarding hooks
  const { data: onboardingProgress } = useOnboardingProgress(workspace?.id || "", !!workspace?.id)

  // Get lead IDs from DB onboarding progress
  const leadIds = useMemo<string[]>(() => {
    return onboardingProgress?.selectedLeadIds || []
  }, [onboardingProgress])

  // Map emails from DB to display format
  const emails = useMemo(() => {
    if (!emailsData?.emails) return []
    return emailsData.emails.map((email) => ({
      id: email.id,
      subject: email.subject || "",
      body: email.bodyText || "",
      leadId: email.leadId || "",
      leadName:
        email.leadName || email.toEmail !== "trial@preview.local"
          ? email.toEmail
          : isKorean
            ? "알 수 없음"
            : "Unknown",
    }))
  }, [emailsData?.emails, isKorean])

  // Check if generation is complete (emails exist in DB)
  const hasEmails = emails.length > 0
  const isGenerationComplete = hasEmails

  // Poll for emails if not yet available
  useEffect(() => {
    if (isGenerationComplete || isLoadingEmails) return

    // Not complete yet, poll for updates
    const pollInterval = setInterval(() => {
      console.log("[StepEmailGeneration] Polling for generated emails...")
      refetchEmails()
    }, POLL_INTERVAL_MS)

    return () => clearInterval(pollInterval)
  }, [isGenerationComplete, isLoadingEmails, refetchEmails])

  const handleNext = () => {
    // TODO: CHANGE STEP 4 -> STEP 3 AFTER DEVELOPING MOST FEATURES FOR NORMAL EMAIL LINKING FLOW
    setSearchParams({ step: "4" })
  }

  // Calculate display values
  const leadCount = leadIds.length
  const templateCount =
    emails.length > 0 && leadCount > 0 ? Math.ceil(emails.length / leadCount) : emails.length

  return (
    <div className="max-w-2xl mx-auto">
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl flex items-center gap-3">
            <Sparkles className="w-6 h-6 text-purple-500" />
            {t("app.onboarding.step3.generatingTitle", "AI 이메일 생성 중")}
          </CardTitle>
          <p className="text-sm text-gray-600 mt-1">
            {t(
              "app.onboarding.step3.generatingDescription",
              "잠재 고객에게 보낼 맞춤형 이메일을 생성하고 있습니다",
            )}
          </p>
        </CardHeader>
        <CardContent className="space-y-6">
          {isLoadingEmails || !isGenerationComplete ? (
            // Generating state - waiting for backend auto-generation
            <div className="py-8 space-y-6">
              <div className="flex flex-col items-center">
                <div className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mb-4">
                  <Loader2 className="w-8 h-8 text-purple-500 animate-spin" />
                </div>
                <p className="text-lg font-medium text-gray-900">
                  {t("app.onboarding.step3.generating", "생성 중...")}
                </p>
                <p className="text-sm text-gray-500 mt-1">
                  {isKorean
                    ? "AI가 이메일을 생성하고 있습니다. 잠시만 기다려주세요..."
                    : "AI is generating emails. Please wait..."}
                </p>
              </div>
              <Progress value={isLoadingEmails ? 40 : 80} className="h-2" />
              <p className="text-center text-sm text-gray-500">
                {isKorean
                  ? "리드 탐색 및 이메일 템플릿 생성 중..."
                  : "Discovering leads and generating email templates..."}
              </p>

              {/* Next Button - allow skipping while generating */}
              <div className="flex justify-end pt-4">
                <Button onClick={handleNext} variant="outline">
                  {isKorean ? "건너뛰기" : "Skip"}
                  <ArrowRight className="w-4 h-4 ml-2" />
                </Button>
              </div>
            </div>
          ) : (
            // Generation complete - show results
            <div className="space-y-6">
              <div className="flex items-center gap-3 p-4 bg-green-50 rounded-lg border border-green-200">
                <CheckCircle2 className="w-6 h-6 text-green-600 flex-shrink-0" />
                <div>
                  <p className="font-medium text-green-800">
                    {isKorean
                      ? `${emails.length}개 이메일이 생성되었습니다`
                      : `${emails.length} emails generated successfully`}
                  </p>
                  <p className="text-sm text-green-600 mt-1">
                    {leadCount > 0
                      ? isKorean
                        ? `${leadCount}개 리드 × ${templateCount}개 템플릿`
                        : `${leadCount} leads × ${templateCount} templates`
                      : isKorean
                        ? `${templateCount}개 이메일 템플릿`
                        : `${templateCount} email templates`}
                  </p>
                </div>
              </div>

              {/* Email preview - show first 3 samples */}
              {emails.length > 0 && (
                <div className="space-y-4">
                  <h3 className="font-medium text-gray-900 flex items-center gap-2">
                    <Mail className="w-4 h-4" />
                    {isKorean ? "이메일 미리보기 (샘플)" : "Email Preview (Samples)"}
                  </h3>
                  {emails.slice(0, 3).map((email) => (
                    <button
                      type="button"
                      key={email.id}
                      className="w-full text-left p-4 bg-gray-50 rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-100 transition-colors"
                      onClick={() => setShowFullEmail(true)}
                    >
                      <div className="flex items-center justify-between mb-2">
                        <p className="text-xs text-blue-600 font-medium">{email.leadName}</p>
                      </div>
                      <p className="font-medium text-gray-900 mb-2 text-sm">
                        {isKorean ? "제목:" : "Subject:"} {email.subject}
                      </p>
                      <p className="text-sm text-gray-600 whitespace-pre-line line-clamp-3">
                        {email.body}
                      </p>
                    </button>
                  ))}
                  {emails.length > 3 && (
                    <p className="text-sm text-gray-500 text-center">
                      {isKorean
                        ? `+${emails.length - 3}개 이메일 더 있음`
                        : `+${emails.length - 3} more emails`}
                    </p>
                  )}

                  {/* View All Button */}
                  <button
                    type="button"
                    onClick={() => setShowFullEmail(true)}
                    className="w-full p-3 border border-gray-200 rounded-lg text-center text-sm text-blue-600 hover:bg-gray-50 transition-colors flex items-center justify-center gap-2"
                  >
                    <Eye className="w-4 h-4" />
                    {isKorean ? "전체 이메일 보기" : "View All Emails"}
                  </button>

                  {/* Full Email Dialog - Show All Emails */}
                  <Dialog open={showFullEmail} onOpenChange={setShowFullEmail}>
                    <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
                      <DialogHeader>
                        <DialogTitle className="flex items-center gap-2">
                          <Mail className="w-5 h-5 text-blue-600" />
                          {isKorean
                            ? `전체 이메일 보기 (${emails.length}개)`
                            : `All Emails (${emails.length})`}
                        </DialogTitle>
                      </DialogHeader>
                      <div className="space-y-4 pt-4 max-h-[60vh] overflow-y-auto">
                        {emails.map((email, index) => (
                          <div
                            key={email.id}
                            className="p-4 bg-gray-50 rounded-lg border border-gray-200"
                          >
                            <div className="flex items-center justify-between mb-2">
                              <span className="text-xs font-medium text-blue-600">
                                #{index + 1} - {email.leadName}
                              </span>
                            </div>
                            <div className="mb-2">
                              <p className="text-xs text-gray-500 mb-1">
                                {isKorean ? "제목" : "Subject"}
                              </p>
                              <p className="font-medium text-gray-900 text-sm">{email.subject}</p>
                            </div>
                            <div>
                              <p className="text-xs text-gray-500 mb-1">
                                {isKorean ? "본문" : "Body"}
                              </p>
                              <p className="text-gray-800 whitespace-pre-line text-sm leading-relaxed line-clamp-6">
                                {email.body}
                              </p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </DialogContent>
                  </Dialog>
                </div>
              )}

              {/* Next Button */}
              <div className="flex justify-end pt-4">
                <Button onClick={handleNext} className="bg-blue-600 hover:bg-blue-700">
                  {t("app.onboarding.step1.nextButton", "다음 단계")}
                  <ArrowRight className="w-4 h-4 ml-2" />
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
