import {
  AlertCircle,
  ArrowRight,
  CheckCircle2,
  Eye,
  Loader2,
  Mail,
  RefreshCw,
  Sparkles,
} from "lucide-react"
import { useEffect, useMemo, useRef, useState } from "react"
import { useTranslation } from "react-i18next"
import { useSearchParams } from "react-router-dom"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Progress } from "@/components/ui/progress"
import { useEmails } from "@/lib/api/hooks/emails"
import { useOnboardingProgress } from "@/lib/api/hooks/onboarding"
import { useUserWorkspaces } from "@/lib/api/hooks/workspaces"

// Polling interval for checking generation status (5 seconds)
const POLL_INTERVAL_MS = 5000
// Maximum polling attempts (60 times = 5 minutes)
const MAX_POLL_ATTEMPTS = 60

export function StepEmailGeneration() {
  const { t, i18n } = useTranslation()
  const [, setSearchParams] = useSearchParams()
  const [showFullEmail, setShowFullEmail] = useState(false)
  const [progress, setProgress] = useState(0)
  const [pollCount, setPollCount] = useState(0)
  const [isTimeout, setIsTimeout] = useState(false)
  const startTimeRef = useRef<number | null>(null)

  console.log("[StepEmailGeneration] Component rendered")

  // Get user's workspace
  const currentUser = useMemo(() => JSON.parse(localStorage.getItem("user") || "{}"), [])
  const userId = currentUser?.id || ""
  const { data: userWorkspaces } = useUserWorkspaces(!!userId)
  const workspace = userWorkspaces?.[0]
  const isKorean = i18n.language === "ko"

  console.log("[StepEmailGeneration] workspace:", workspace?.id)

  // Onboarding hooks - fetch first to get sequenceId
  const { data: onboardingProgress } = useOnboardingProgress(workspace?.id || "", !!workspace?.id)

  // Fetch emails from DB - these are the preview emails generated by autoGenerateOnboarding
  // Filter by sequenceId to only show onboarding emails
  const sequenceId = onboardingProgress?.generatedSequenceId || ""

  const {
    data: emailsData,
    isLoading: isLoadingEmails,
    refetch: refetchEmails,
  } = useEmails({
    workspaceId: workspace?.id || "",
    sequenceId: sequenceId || undefined,
    limit: 700, // 300 leads × 2 steps = 600 emails max
  })

  // Get lead IDs from DB onboarding progress
  const leadIds = useMemo<string[]>(
    () => onboardingProgress?.selectedLeadIds || [],
    [onboardingProgress],
  )

  // Map emails from DB to display format
  const emails = useMemo(() => {
    if (!emailsData?.emails) {
      console.log("[StepEmailGeneration] No emails data yet")
      return []
    }
    console.log(`[StepEmailGeneration] Mapping ${emailsData.emails.length} emails from DB`)
    return emailsData.emails.map((email) => ({
      id: email.id,
      subject: email.subject || "",
      body: email.bodyText || "",
      leadId: email.leadId || "",
      leadName:
        email.leadName || email.toEmail !== "trial@preview.local"
          ? email.toEmail
          : isKorean
            ? "알 수 없음"
            : "Unknown",
    }))
  }, [emailsData?.emails, isKorean])

  // Check job status and generation state
  const jobStatus = onboardingProgress?.jobStatus
  const hasEmails = emails.length > 0
  const isGenerationComplete = hasEmails
  const isJobFailed = jobStatus === "failed" || jobStatus === "stalled"

  console.log("[StepEmailGeneration] Status:", {
    hasEmails,
    isGenerationComplete,
    isLoadingEmails,
    emailCount: emails.length,
    leadCount: leadIds.length,
    jobStatus,
    pollCount,
    isTimeout,
  })

  // Poll for emails if not yet available
  useEffect(() => {
    // Stop polling if generation is complete
    if (isGenerationComplete) {
      console.log(`[StepEmailGeneration] ✅ Generation complete! ${emails.length} emails loaded`)
      return
    }

    // Stop polling if job failed
    if (isJobFailed) {
      console.log("[StepEmailGeneration] ❌ Job failed, stopping polling")
      return
    }

    // Stop polling if timeout
    if (isTimeout) {
      console.log("[StepEmailGeneration] ⏱️ Timeout reached, stopping polling")
      return
    }

    // Stop polling if max attempts reached
    if (pollCount >= MAX_POLL_ATTEMPTS) {
      console.log(
        `[StepEmailGeneration] ⏱️ Max polling attempts (${MAX_POLL_ATTEMPTS}) reached, timeout`,
      )
      setIsTimeout(true)
      return
    }

    if (isLoadingEmails) {
      console.log("[StepEmailGeneration] Loading emails...")
      return
    }

    // Not complete yet, poll for updates
    console.log(
      `[StepEmailGeneration] Starting polling interval... (attempt ${pollCount + 1}/${MAX_POLL_ATTEMPTS})`,
    )
    const pollInterval = setInterval(() => {
      console.log(
        `[StepEmailGeneration] Polling for generated emails... (${pollCount + 1}/${MAX_POLL_ATTEMPTS})`,
      )
      setPollCount((prev) => prev + 1)
      refetchEmails()
    }, POLL_INTERVAL_MS)

    return () => {
      console.log("[StepEmailGeneration] Clearing polling interval")
      clearInterval(pollInterval)
    }
  }, [
    isGenerationComplete,
    isJobFailed,
    isTimeout,
    pollCount,
    isLoadingEmails,
    refetchEmails,
    emails.length,
  ])

  // Exponential decay progress bar - slows down as it approaches completion
  // Formula: progress = 100 * (1 - e^(-t/τ)) where τ is the time constant
  useEffect(() => {
    if (isGenerationComplete) {
      setProgress(100)
      startTimeRef.current = null
      return
    }

    // Initialize start time
    if (!startTimeRef.current) {
      startTimeRef.current = Date.now()
    }

    const interval = setInterval(() => {
      if (!startTimeRef.current) {
        return
      }

      const elapsed = (Date.now() - startTimeRef.current) / 1000 // seconds
      const tau = 25 // time constant - controls how fast progress grows (lower = faster initial growth)
      // Exponential decay formula: approaches 95% asymptotically, never quite reaching it
      const newProgress = Math.min(95, 100 * (1 - Math.exp(-elapsed / tau)))
      setProgress(Math.round(newProgress))
    }, 100)

    return () => clearInterval(interval)
  }, [isGenerationComplete])

  const handleNext = () => {
    setSearchParams({ step: "4" })
  }

  const handleRetry = () => {
    // Reset polling state
    setPollCount(0)
    setIsTimeout(false)
    startTimeRef.current = Date.now()
    setProgress(0)
    // Refetch to restart polling
    refetchEmails()
  }

  const handleBackToLeadSearch = () => {
    setSearchParams({ step: "2" })
  }

  // Calculate display values
  const leadCount = leadIds.length
  const templateCount =
    emails.length > 0 && leadCount > 0 ? Math.ceil(emails.length / leadCount) : emails.length

  return (
    <div className="mx-auto max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-3 text-2xl">
            <Sparkles className="h-6 w-6 text-blue-500" />
            {t("app.onboarding.step3.generatingTitle", "AI 이메일 생성 중")}
          </CardTitle>
          <p className="mt-1 text-gray-600 text-sm">
            {t(
              "app.onboarding.step3.generatingDescription",
              "잠재 고객에게 보낼 맞춤형 이메일을 생성하고 있습니다",
            )}
          </p>
        </CardHeader>
        <CardContent className="space-y-6">
          {isJobFailed ? (
            // Job failed state
            <div className="space-y-6 py-8">
              <div className="flex flex-col items-center">
                <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-red-100">
                  <AlertCircle className="h-8 w-8 text-red-500" />
                </div>
                <p className="font-medium text-gray-900 text-lg">
                  {isKorean ? "이메일 생성에 실패했어요" : "Email generation failed"}
                </p>
                <p className="mt-2 max-w-md text-center text-gray-500 text-sm leading-relaxed">
                  {isKorean
                    ? "AI 서비스 오류 또는 일시적인 문제로 이메일 생성에 실패했습니다. 잠시 후 다시 시도해주세요."
                    : "Failed to generate emails due to AI service error or temporary issue. Please try again later."}
                </p>
              </div>
              <div className="flex gap-3">
                <Button
                  className="h-12 flex-1 rounded-xl border-gray-200"
                  onClick={handleBackToLeadSearch}
                  variant="outline"
                >
                  {isKorean ? "이전 단계로" : "Go back"}
                </Button>
                <Button
                  className="h-12 flex-1 rounded-xl bg-blue-500 hover:bg-blue-600"
                  onClick={handleRetry}
                >
                  <RefreshCw className="mr-2 h-4 w-4" />
                  {isKorean ? "다시 시도" : "Retry"}
                </Button>
              </div>
            </div>
          ) : isTimeout ? (
            // Timeout state
            <div className="space-y-6 py-8">
              <div className="flex flex-col items-center">
                <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-amber-100">
                  <AlertCircle className="h-8 w-8 text-amber-500" />
                </div>
                <p className="font-medium text-gray-900 text-lg">
                  {isKorean ? "시간이 너무 오래 걸리고 있어요" : "Taking longer than expected"}
                </p>
                <p className="mt-2 max-w-md text-center text-gray-500 text-sm leading-relaxed">
                  {isKorean
                    ? "5분이 지났지만 아직 완료되지 않았습니다. 백그라운드에서 작업이 진행 중일 수 있습니다. 잠시 후 다시 확인하거나 처음부터 다시 시도해주세요."
                    : "It's been 5 minutes but generation is not complete. The task might still be running in the background. Please check back later or restart from the beginning."}
                </p>
              </div>
              <div className="flex gap-3">
                <Button
                  className="h-12 flex-1 rounded-xl border-gray-200"
                  onClick={handleBackToLeadSearch}
                  variant="outline"
                >
                  {isKorean ? "이전 단계로" : "Go back"}
                </Button>
                <Button
                  className="h-12 flex-1 rounded-xl bg-blue-500 hover:bg-blue-600"
                  onClick={handleRetry}
                >
                  <RefreshCw className="mr-2 h-4 w-4" />
                  {isKorean ? "다시 확인" : "Check again"}
                </Button>
              </div>
            </div>
          ) : isLoadingEmails || !isGenerationComplete ? (
            // Generating state - waiting for backend auto-generation
            <div className="space-y-6 py-8">
              <div className="flex flex-col items-center">
                <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-blue-100">
                  <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
                </div>
                <p className="font-medium text-gray-900 text-lg">
                  {t("app.onboarding.step3.generating", "생성 중...")}
                </p>
                <p className="mt-1 text-gray-500 text-sm">
                  {isKorean
                    ? "AI가 이메일을 생성하고 있습니다. 잠시만 기다려주세요..."
                    : "AI is generating emails. Please wait..."}
                </p>
              </div>
              <Progress className="h-2" value={progress} />
              <div className="space-y-1">
                <p className="text-center text-gray-500 text-sm">
                  {isKorean
                    ? "리드 탐색 및 이메일 템플릿 생성 중..."
                    : "Discovering leads and generating email templates..."}
                </p>
                {pollCount > 0 && (
                  <p className="text-center text-gray-400 text-xs">
                    {isKorean
                      ? `확인 중... (${pollCount}/${MAX_POLL_ATTEMPTS})`
                      : `Checking... (${pollCount}/${MAX_POLL_ATTEMPTS})`}
                  </p>
                )}
              </div>
            </div>
          ) : (
            // Generation complete - show results
            <div className="space-y-6">
              <div className="flex items-center gap-3 rounded-lg border border-green-200 bg-green-50 p-4">
                <CheckCircle2 className="h-6 w-6 flex-shrink-0 text-green-600" />
                <div>
                  <p className="font-medium text-green-800">
                    {isKorean
                      ? `${emails.length}개 이메일이 생성되었습니다`
                      : `${emails.length} emails generated successfully`}
                  </p>
                  <p className="mt-1 text-green-600 text-sm">
                    {leadCount > 0
                      ? isKorean
                        ? `${leadCount}개 리드 × ${templateCount}개 템플릿`
                        : `${leadCount} leads × ${templateCount} templates`
                      : isKorean
                        ? `${templateCount}개 이메일 템플릿`
                        : `${templateCount} email templates`}
                  </p>
                </div>
              </div>

              {/* Email preview - show first 3 samples */}
              {emails.length > 0 && (
                <div className="space-y-4">
                  <h3 className="flex items-center gap-2 font-medium text-gray-900">
                    <Mail className="h-4 w-4" />
                    {isKorean ? "이메일 미리보기 (샘플)" : "Email Preview (Samples)"}
                  </h3>
                  {emails.slice(0, 3).map((email) => (
                    <button
                      className="w-full cursor-pointer rounded-lg border border-gray-200 bg-gray-50 p-4 text-left transition-colors hover:bg-gray-100"
                      key={email.id}
                      onClick={() => setShowFullEmail(true)}
                      type="button"
                    >
                      <div className="mb-2 flex items-center justify-between">
                        <p className="font-medium text-blue-600 text-xs">{email.leadName}</p>
                      </div>
                      <p className="mb-2 font-medium text-gray-900 text-sm">
                        {isKorean ? "제목:" : "Subject:"} {email.subject}
                      </p>
                      <p className="line-clamp-3 whitespace-pre-line text-gray-600 text-sm">
                        {email.body}
                      </p>
                    </button>
                  ))}
                  {emails.length > 3 && (
                    <p className="text-center text-gray-500 text-sm">
                      {isKorean
                        ? `+${emails.length - 3}개 이메일 더 있음`
                        : `+${emails.length - 3} more emails`}
                    </p>
                  )}

                  {/* View All Button */}
                  <button
                    className="flex w-full items-center justify-center gap-2 rounded-lg border border-gray-200 p-3 text-center text-blue-600 text-sm transition-colors hover:bg-gray-50"
                    onClick={() => setShowFullEmail(true)}
                    type="button"
                  >
                    <Eye className="h-4 w-4" />
                    {isKorean ? "전체 이메일 보기" : "View All Emails"}
                  </button>

                  {/* Full Email Dialog - Show All Emails */}
                  <Dialog onOpenChange={setShowFullEmail} open={showFullEmail}>
                    <DialogContent className="max-h-[90vh] max-w-4xl">
                      <DialogHeader className="border-gray-200 border-b pb-4">
                        <DialogTitle className="flex items-center gap-2">
                          <Mail className="h-5 w-5 text-blue-600" />
                          {isKorean
                            ? `생성된 이메일 (${emails.length}개)`
                            : `Generated Emails (${emails.length})`}
                        </DialogTitle>
                        <p className="mt-1 text-gray-500 text-sm">
                          {isKorean
                            ? `${leadCount}명의 바이어에게 발송될 맞춤 이메일입니다`
                            : `Personalized emails for ${leadCount} buyers`}
                        </p>
                      </DialogHeader>
                      <div className="max-h-[70vh] space-y-3 overflow-y-auto py-4">
                        {emails.map((email, index) => (
                          <details
                            className="group rounded-lg border border-gray-200 bg-white"
                            key={email.id}
                          >
                            <summary className="flex cursor-pointer items-center justify-between p-4 hover:bg-gray-50">
                              <div className="flex items-center gap-3">
                                <span className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-blue-100 font-medium text-blue-600 text-xs">
                                  {index + 1}
                                </span>
                                <div className="min-w-0">
                                  <p className="truncate font-medium text-gray-900 text-sm">
                                    {email.leadName}
                                  </p>
                                  <p className="truncate text-gray-500 text-xs">{email.subject}</p>
                                </div>
                              </div>
                              <span className="text-gray-400 text-xs group-open:rotate-180">▼</span>
                            </summary>
                            <div className="border-gray-200 border-t bg-gray-50 p-4">
                              <div className="mb-3">
                                <p className="mb-1 font-medium text-gray-500 text-xs uppercase tracking-wide">
                                  {isKorean ? "제목" : "Subject"}
                                </p>
                                <p className="font-medium text-gray-900">{email.subject}</p>
                              </div>
                              <div>
                                <p className="mb-1 font-medium text-gray-500 text-xs uppercase tracking-wide">
                                  {isKorean ? "본문" : "Body"}
                                </p>
                                <div className="whitespace-pre-line rounded-md bg-white p-3 text-gray-800 text-sm leading-relaxed">
                                  {email.body || (
                                    <span className="text-gray-400 italic">
                                      {isKorean ? "(본문 없음)" : "(No content)"}
                                    </span>
                                  )}
                                </div>
                              </div>
                            </div>
                          </details>
                        ))}
                      </div>
                    </DialogContent>
                  </Dialog>
                </div>
              )}

              {/* Next Button */}
              <div className="flex justify-end pt-4">
                <Button className="bg-blue-600 hover:bg-blue-700" onClick={handleNext}>
                  {t("app.onboarding.step1.nextButton", "다음 단계")}
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
