// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addUserEditLanguageStmt, err = db.PrepareContext(ctx, addUserEditLanguage); err != nil {
		return nil, fmt.Errorf("error preparing query AddUserEditLanguage: %w", err)
	}
	if q.addUserReviewLanguageStmt, err = db.PrepareContext(ctx, addUserReviewLanguage); err != nil {
		return nil, fmt.Errorf("error preparing query AddUserReviewLanguage: %w", err)
	}
	if q.checkAccountExistsStmt, err = db.PrepareContext(ctx, checkAccountExists); err != nil {
		return nil, fmt.Errorf("error preparing query CheckAccountExists: %w", err)
	}
	if q.countActiveLanguagesStmt, err = db.PrepareContext(ctx, countActiveLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query CountActiveLanguages: %w", err)
	}
	if q.countAllTranslationsStmt, err = db.PrepareContext(ctx, countAllTranslations); err != nil {
		return nil, fmt.Errorf("error preparing query CountAllTranslations: %w", err)
	}
	if q.countLanguagesStmt, err = db.PrepareContext(ctx, countLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query CountLanguages: %w", err)
	}
	if q.countTranslationsByLanguageStmt, err = db.PrepareContext(ctx, countTranslationsByLanguage); err != nil {
		return nil, fmt.Errorf("error preparing query CountTranslationsByLanguage: %w", err)
	}
	if q.countTranslationsByReviewStatusStmt, err = db.PrepareContext(ctx, countTranslationsByReviewStatus); err != nil {
		return nil, fmt.Errorf("error preparing query CountTranslationsByReviewStatus: %w", err)
	}
	if q.countTranslationsBySearchStmt, err = db.PrepareContext(ctx, countTranslationsBySearch); err != nil {
		return nil, fmt.Errorf("error preparing query CountTranslationsBySearch: %w", err)
	}
	if q.countTranslationsByUserStmt, err = db.PrepareContext(ctx, countTranslationsByUser); err != nil {
		return nil, fmt.Errorf("error preparing query CountTranslationsByUser: %w", err)
	}
	if q.countTranslationsWithFiltersStmt, err = db.PrepareContext(ctx, countTranslationsWithFilters); err != nil {
		return nil, fmt.Errorf("error preparing query CountTranslationsWithFilters: %w", err)
	}
	if q.countTranslationsWithMultipleFiltersStmt, err = db.PrepareContext(ctx, countTranslationsWithMultipleFilters); err != nil {
		return nil, fmt.Errorf("error preparing query CountTranslationsWithMultipleFilters: %w", err)
	}
	if q.countUniqueSourceTextsWithFiltersStmt, err = db.PrepareContext(ctx, countUniqueSourceTextsWithFilters); err != nil {
		return nil, fmt.Errorf("error preparing query CountUniqueSourceTextsWithFilters: %w", err)
	}
	if q.countUsersStmt, err = db.PrepareContext(ctx, countUsers); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsers: %w", err)
	}
	if q.countUsersByDepartmentStmt, err = db.PrepareContext(ctx, countUsersByDepartment); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsersByDepartment: %w", err)
	}
	if q.countUsersWithFiltersStmt, err = db.PrepareContext(ctx, countUsersWithFilters); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsersWithFilters: %w", err)
	}
	if q.countUsersWithMultiFiltersStmt, err = db.PrepareContext(ctx, countUsersWithMultiFilters); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsersWithMultiFilters: %w", err)
	}
	if q.createDepartmentStmt, err = db.PrepareContext(ctx, createDepartment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDepartment: %w", err)
	}
	if q.createLanguageStmt, err = db.PrepareContext(ctx, createLanguage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLanguage: %w", err)
	}
	if q.createOrUpdateGoogleUserStmt, err = db.PrepareContext(ctx, createOrUpdateGoogleUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrUpdateGoogleUser: %w", err)
	}
	if q.createTranslationStmt, err = db.PrepareContext(ctx, createTranslation); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTranslation: %w", err)
	}
	if q.createTranslationReviewStmt, err = db.PrepareContext(ctx, createTranslationReview); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTranslationReview: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteDepartmentStmt, err = db.PrepareContext(ctx, deleteDepartment); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDepartment: %w", err)
	}
	if q.deleteLanguageStmt, err = db.PrepareContext(ctx, deleteLanguage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLanguage: %w", err)
	}
	if q.deleteTranslationStmt, err = db.PrepareContext(ctx, deleteTranslation); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTranslation: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getApprovedTranslationStmt, err = db.PrepareContext(ctx, getApprovedTranslation); err != nil {
		return nil, fmt.Errorf("error preparing query GetApprovedTranslation: %w", err)
	}
	if q.getAssignableUsersStmt, err = db.PrepareContext(ctx, getAssignableUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetAssignableUsers: %w", err)
	}
	if q.getDepartmentStmt, err = db.PrepareContext(ctx, getDepartment); err != nil {
		return nil, fmt.Errorf("error preparing query GetDepartment: %w", err)
	}
	if q.getLanguageStmt, err = db.PrepareContext(ctx, getLanguage); err != nil {
		return nil, fmt.Errorf("error preparing query GetLanguage: %w", err)
	}
	if q.getLanguageByCodeStmt, err = db.PrepareContext(ctx, getLanguageByCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetLanguageByCode: %w", err)
	}
	if q.getTranslationStmt, err = db.PrepareContext(ctx, getTranslation); err != nil {
		return nil, fmt.Errorf("error preparing query GetTranslation: %w", err)
	}
	if q.getTranslationBySourceAndTargetStmt, err = db.PrepareContext(ctx, getTranslationBySourceAndTarget); err != nil {
		return nil, fmt.Errorf("error preparing query GetTranslationBySourceAndTarget: %w", err)
	}
	if q.getTranslationReviewStatusStmt, err = db.PrepareContext(ctx, getTranslationReviewStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetTranslationReviewStatus: %w", err)
	}
	if q.getTranslationWithContextStmt, err = db.PrepareContext(ctx, getTranslationWithContext); err != nil {
		return nil, fmt.Errorf("error preparing query GetTranslationWithContext: %w", err)
	}
	if q.getTranslationsByContextKeyStmt, err = db.PrepareContext(ctx, getTranslationsByContextKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetTranslationsByContextKey: %w", err)
	}
	if q.getTranslationsBySourceTextsStmt, err = db.PrepareContext(ctx, getTranslationsBySourceTexts); err != nil {
		return nil, fmt.Errorf("error preparing query GetTranslationsBySourceTexts: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserEditLanguagesStmt, err = db.PrepareContext(ctx, getUserEditLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserEditLanguages: %w", err)
	}
	if q.getUserReviewLanguagesStmt, err = db.PrepareContext(ctx, getUserReviewLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserReviewLanguages: %w", err)
	}
	if q.getUserWithEditLanguagesStmt, err = db.PrepareContext(ctx, getUserWithEditLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserWithEditLanguages: %w", err)
	}
	if q.getUserWithLanguagesStmt, err = db.PrepareContext(ctx, getUserWithLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserWithLanguages: %w", err)
	}
	if q.getUsersWithLanguagePermissionsStmt, err = db.PrepareContext(ctx, getUsersWithLanguagePermissions); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsersWithLanguagePermissions: %w", err)
	}
	if q.listActiveLanguagesStmt, err = db.PrepareContext(ctx, listActiveLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveLanguages: %w", err)
	}
	if q.listAllDepartmentsStmt, err = db.PrepareContext(ctx, listAllDepartments); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllDepartments: %w", err)
	}
	if q.listDepartmentsStmt, err = db.PrepareContext(ctx, listDepartments); err != nil {
		return nil, fmt.Errorf("error preparing query ListDepartments: %w", err)
	}
	if q.listLanguagesStmt, err = db.PrepareContext(ctx, listLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query ListLanguages: %w", err)
	}
	if q.listTranslationsStmt, err = db.PrepareContext(ctx, listTranslations); err != nil {
		return nil, fmt.Errorf("error preparing query ListTranslations: %w", err)
	}
	if q.listTranslationsByLanguageStmt, err = db.PrepareContext(ctx, listTranslationsByLanguage); err != nil {
		return nil, fmt.Errorf("error preparing query ListTranslationsByLanguage: %w", err)
	}
	if q.listTranslationsByReviewStatusStmt, err = db.PrepareContext(ctx, listTranslationsByReviewStatus); err != nil {
		return nil, fmt.Errorf("error preparing query ListTranslationsByReviewStatus: %w", err)
	}
	if q.listTranslationsByUserStmt, err = db.PrepareContext(ctx, listTranslationsByUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListTranslationsByUser: %w", err)
	}
	if q.listTranslationsWithFiltersStmt, err = db.PrepareContext(ctx, listTranslationsWithFilters); err != nil {
		return nil, fmt.Errorf("error preparing query ListTranslationsWithFilters: %w", err)
	}
	if q.listTranslationsWithMultipleFiltersStmt, err = db.PrepareContext(ctx, listTranslationsWithMultipleFilters); err != nil {
		return nil, fmt.Errorf("error preparing query ListTranslationsWithMultipleFilters: %w", err)
	}
	if q.listUniqueSourceTextsWithFiltersStmt, err = db.PrepareContext(ctx, listUniqueSourceTextsWithFilters); err != nil {
		return nil, fmt.Errorf("error preparing query ListUniqueSourceTextsWithFilters: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.listUsersWithFiltersStmt, err = db.PrepareContext(ctx, listUsersWithFilters); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsersWithFilters: %w", err)
	}
	if q.listUsersWithMultiFiltersStmt, err = db.PrepareContext(ctx, listUsersWithMultiFilters); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsersWithMultiFilters: %w", err)
	}
	if q.removeAllUserEditLanguagesStmt, err = db.PrepareContext(ctx, removeAllUserEditLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveAllUserEditLanguages: %w", err)
	}
	if q.removeAllUserReviewLanguagesStmt, err = db.PrepareContext(ctx, removeAllUserReviewLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveAllUserReviewLanguages: %w", err)
	}
	if q.removeUserEditLanguageStmt, err = db.PrepareContext(ctx, removeUserEditLanguage); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveUserEditLanguage: %w", err)
	}
	if q.removeUserReviewLanguageStmt, err = db.PrepareContext(ctx, removeUserReviewLanguage); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveUserReviewLanguage: %w", err)
	}
	if q.searchTranslationsStmt, err = db.PrepareContext(ctx, searchTranslations); err != nil {
		return nil, fmt.Errorf("error preparing query SearchTranslations: %w", err)
	}
	if q.setUserEditLanguagesStmt, err = db.PrepareContext(ctx, setUserEditLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query SetUserEditLanguages: %w", err)
	}
	if q.setUserReviewLanguagesStmt, err = db.PrepareContext(ctx, setUserReviewLanguages); err != nil {
		return nil, fmt.Errorf("error preparing query SetUserReviewLanguages: %w", err)
	}
	if q.updateDepartmentStmt, err = db.PrepareContext(ctx, updateDepartment); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDepartment: %w", err)
	}
	if q.updateLanguageStmt, err = db.PrepareContext(ctx, updateLanguage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateLanguage: %w", err)
	}
	if q.updateLastLoginStmt, err = db.PrepareContext(ctx, updateLastLogin); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateLastLogin: %w", err)
	}
	if q.updateTranslationStmt, err = db.PrepareContext(ctx, updateTranslation); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTranslation: %w", err)
	}
	if q.updateTranslationContextStmt, err = db.PrepareContext(ctx, updateTranslationContext); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTranslationContext: %w", err)
	}
	if q.updateTranslationReviewStatusStmt, err = db.PrepareContext(ctx, updateTranslationReviewStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTranslationReviewStatus: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	if q.upsertTranslationStmt, err = db.PrepareContext(ctx, upsertTranslation); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertTranslation: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addUserEditLanguageStmt != nil {
		if cerr := q.addUserEditLanguageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addUserEditLanguageStmt: %w", cerr)
		}
	}
	if q.addUserReviewLanguageStmt != nil {
		if cerr := q.addUserReviewLanguageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addUserReviewLanguageStmt: %w", cerr)
		}
	}
	if q.checkAccountExistsStmt != nil {
		if cerr := q.checkAccountExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkAccountExistsStmt: %w", cerr)
		}
	}
	if q.countActiveLanguagesStmt != nil {
		if cerr := q.countActiveLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countActiveLanguagesStmt: %w", cerr)
		}
	}
	if q.countAllTranslationsStmt != nil {
		if cerr := q.countAllTranslationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAllTranslationsStmt: %w", cerr)
		}
	}
	if q.countLanguagesStmt != nil {
		if cerr := q.countLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countLanguagesStmt: %w", cerr)
		}
	}
	if q.countTranslationsByLanguageStmt != nil {
		if cerr := q.countTranslationsByLanguageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTranslationsByLanguageStmt: %w", cerr)
		}
	}
	if q.countTranslationsByReviewStatusStmt != nil {
		if cerr := q.countTranslationsByReviewStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTranslationsByReviewStatusStmt: %w", cerr)
		}
	}
	if q.countTranslationsBySearchStmt != nil {
		if cerr := q.countTranslationsBySearchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTranslationsBySearchStmt: %w", cerr)
		}
	}
	if q.countTranslationsByUserStmt != nil {
		if cerr := q.countTranslationsByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTranslationsByUserStmt: %w", cerr)
		}
	}
	if q.countTranslationsWithFiltersStmt != nil {
		if cerr := q.countTranslationsWithFiltersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTranslationsWithFiltersStmt: %w", cerr)
		}
	}
	if q.countTranslationsWithMultipleFiltersStmt != nil {
		if cerr := q.countTranslationsWithMultipleFiltersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTranslationsWithMultipleFiltersStmt: %w", cerr)
		}
	}
	if q.countUniqueSourceTextsWithFiltersStmt != nil {
		if cerr := q.countUniqueSourceTextsWithFiltersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUniqueSourceTextsWithFiltersStmt: %w", cerr)
		}
	}
	if q.countUsersStmt != nil {
		if cerr := q.countUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersStmt: %w", cerr)
		}
	}
	if q.countUsersByDepartmentStmt != nil {
		if cerr := q.countUsersByDepartmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersByDepartmentStmt: %w", cerr)
		}
	}
	if q.countUsersWithFiltersStmt != nil {
		if cerr := q.countUsersWithFiltersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersWithFiltersStmt: %w", cerr)
		}
	}
	if q.countUsersWithMultiFiltersStmt != nil {
		if cerr := q.countUsersWithMultiFiltersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersWithMultiFiltersStmt: %w", cerr)
		}
	}
	if q.createDepartmentStmt != nil {
		if cerr := q.createDepartmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDepartmentStmt: %w", cerr)
		}
	}
	if q.createLanguageStmt != nil {
		if cerr := q.createLanguageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLanguageStmt: %w", cerr)
		}
	}
	if q.createOrUpdateGoogleUserStmt != nil {
		if cerr := q.createOrUpdateGoogleUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrUpdateGoogleUserStmt: %w", cerr)
		}
	}
	if q.createTranslationStmt != nil {
		if cerr := q.createTranslationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTranslationStmt: %w", cerr)
		}
	}
	if q.createTranslationReviewStmt != nil {
		if cerr := q.createTranslationReviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTranslationReviewStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteDepartmentStmt != nil {
		if cerr := q.deleteDepartmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDepartmentStmt: %w", cerr)
		}
	}
	if q.deleteLanguageStmt != nil {
		if cerr := q.deleteLanguageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLanguageStmt: %w", cerr)
		}
	}
	if q.deleteTranslationStmt != nil {
		if cerr := q.deleteTranslationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTranslationStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getApprovedTranslationStmt != nil {
		if cerr := q.getApprovedTranslationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getApprovedTranslationStmt: %w", cerr)
		}
	}
	if q.getAssignableUsersStmt != nil {
		if cerr := q.getAssignableUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAssignableUsersStmt: %w", cerr)
		}
	}
	if q.getDepartmentStmt != nil {
		if cerr := q.getDepartmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDepartmentStmt: %w", cerr)
		}
	}
	if q.getLanguageStmt != nil {
		if cerr := q.getLanguageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLanguageStmt: %w", cerr)
		}
	}
	if q.getLanguageByCodeStmt != nil {
		if cerr := q.getLanguageByCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLanguageByCodeStmt: %w", cerr)
		}
	}
	if q.getTranslationStmt != nil {
		if cerr := q.getTranslationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTranslationStmt: %w", cerr)
		}
	}
	if q.getTranslationBySourceAndTargetStmt != nil {
		if cerr := q.getTranslationBySourceAndTargetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTranslationBySourceAndTargetStmt: %w", cerr)
		}
	}
	if q.getTranslationReviewStatusStmt != nil {
		if cerr := q.getTranslationReviewStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTranslationReviewStatusStmt: %w", cerr)
		}
	}
	if q.getTranslationWithContextStmt != nil {
		if cerr := q.getTranslationWithContextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTranslationWithContextStmt: %w", cerr)
		}
	}
	if q.getTranslationsByContextKeyStmt != nil {
		if cerr := q.getTranslationsByContextKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTranslationsByContextKeyStmt: %w", cerr)
		}
	}
	if q.getTranslationsBySourceTextsStmt != nil {
		if cerr := q.getTranslationsBySourceTextsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTranslationsBySourceTextsStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserEditLanguagesStmt != nil {
		if cerr := q.getUserEditLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserEditLanguagesStmt: %w", cerr)
		}
	}
	if q.getUserReviewLanguagesStmt != nil {
		if cerr := q.getUserReviewLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserReviewLanguagesStmt: %w", cerr)
		}
	}
	if q.getUserWithEditLanguagesStmt != nil {
		if cerr := q.getUserWithEditLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserWithEditLanguagesStmt: %w", cerr)
		}
	}
	if q.getUserWithLanguagesStmt != nil {
		if cerr := q.getUserWithLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserWithLanguagesStmt: %w", cerr)
		}
	}
	if q.getUsersWithLanguagePermissionsStmt != nil {
		if cerr := q.getUsersWithLanguagePermissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsersWithLanguagePermissionsStmt: %w", cerr)
		}
	}
	if q.listActiveLanguagesStmt != nil {
		if cerr := q.listActiveLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveLanguagesStmt: %w", cerr)
		}
	}
	if q.listAllDepartmentsStmt != nil {
		if cerr := q.listAllDepartmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllDepartmentsStmt: %w", cerr)
		}
	}
	if q.listDepartmentsStmt != nil {
		if cerr := q.listDepartmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDepartmentsStmt: %w", cerr)
		}
	}
	if q.listLanguagesStmt != nil {
		if cerr := q.listLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLanguagesStmt: %w", cerr)
		}
	}
	if q.listTranslationsStmt != nil {
		if cerr := q.listTranslationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTranslationsStmt: %w", cerr)
		}
	}
	if q.listTranslationsByLanguageStmt != nil {
		if cerr := q.listTranslationsByLanguageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTranslationsByLanguageStmt: %w", cerr)
		}
	}
	if q.listTranslationsByReviewStatusStmt != nil {
		if cerr := q.listTranslationsByReviewStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTranslationsByReviewStatusStmt: %w", cerr)
		}
	}
	if q.listTranslationsByUserStmt != nil {
		if cerr := q.listTranslationsByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTranslationsByUserStmt: %w", cerr)
		}
	}
	if q.listTranslationsWithFiltersStmt != nil {
		if cerr := q.listTranslationsWithFiltersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTranslationsWithFiltersStmt: %w", cerr)
		}
	}
	if q.listTranslationsWithMultipleFiltersStmt != nil {
		if cerr := q.listTranslationsWithMultipleFiltersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTranslationsWithMultipleFiltersStmt: %w", cerr)
		}
	}
	if q.listUniqueSourceTextsWithFiltersStmt != nil {
		if cerr := q.listUniqueSourceTextsWithFiltersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUniqueSourceTextsWithFiltersStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.listUsersWithFiltersStmt != nil {
		if cerr := q.listUsersWithFiltersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersWithFiltersStmt: %w", cerr)
		}
	}
	if q.listUsersWithMultiFiltersStmt != nil {
		if cerr := q.listUsersWithMultiFiltersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersWithMultiFiltersStmt: %w", cerr)
		}
	}
	if q.removeAllUserEditLanguagesStmt != nil {
		if cerr := q.removeAllUserEditLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeAllUserEditLanguagesStmt: %w", cerr)
		}
	}
	if q.removeAllUserReviewLanguagesStmt != nil {
		if cerr := q.removeAllUserReviewLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeAllUserReviewLanguagesStmt: %w", cerr)
		}
	}
	if q.removeUserEditLanguageStmt != nil {
		if cerr := q.removeUserEditLanguageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeUserEditLanguageStmt: %w", cerr)
		}
	}
	if q.removeUserReviewLanguageStmt != nil {
		if cerr := q.removeUserReviewLanguageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeUserReviewLanguageStmt: %w", cerr)
		}
	}
	if q.searchTranslationsStmt != nil {
		if cerr := q.searchTranslationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchTranslationsStmt: %w", cerr)
		}
	}
	if q.setUserEditLanguagesStmt != nil {
		if cerr := q.setUserEditLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setUserEditLanguagesStmt: %w", cerr)
		}
	}
	if q.setUserReviewLanguagesStmt != nil {
		if cerr := q.setUserReviewLanguagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setUserReviewLanguagesStmt: %w", cerr)
		}
	}
	if q.updateDepartmentStmt != nil {
		if cerr := q.updateDepartmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDepartmentStmt: %w", cerr)
		}
	}
	if q.updateLanguageStmt != nil {
		if cerr := q.updateLanguageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateLanguageStmt: %w", cerr)
		}
	}
	if q.updateLastLoginStmt != nil {
		if cerr := q.updateLastLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateLastLoginStmt: %w", cerr)
		}
	}
	if q.updateTranslationStmt != nil {
		if cerr := q.updateTranslationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTranslationStmt: %w", cerr)
		}
	}
	if q.updateTranslationContextStmt != nil {
		if cerr := q.updateTranslationContextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTranslationContextStmt: %w", cerr)
		}
	}
	if q.updateTranslationReviewStatusStmt != nil {
		if cerr := q.updateTranslationReviewStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTranslationReviewStatusStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	if q.upsertTranslationStmt != nil {
		if cerr := q.upsertTranslationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertTranslationStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                       DBTX
	tx                                       *sql.Tx
	addUserEditLanguageStmt                  *sql.Stmt
	addUserReviewLanguageStmt                *sql.Stmt
	checkAccountExistsStmt                   *sql.Stmt
	countActiveLanguagesStmt                 *sql.Stmt
	countAllTranslationsStmt                 *sql.Stmt
	countLanguagesStmt                       *sql.Stmt
	countTranslationsByLanguageStmt          *sql.Stmt
	countTranslationsByReviewStatusStmt      *sql.Stmt
	countTranslationsBySearchStmt            *sql.Stmt
	countTranslationsByUserStmt              *sql.Stmt
	countTranslationsWithFiltersStmt         *sql.Stmt
	countTranslationsWithMultipleFiltersStmt *sql.Stmt
	countUniqueSourceTextsWithFiltersStmt    *sql.Stmt
	countUsersStmt                           *sql.Stmt
	countUsersByDepartmentStmt               *sql.Stmt
	countUsersWithFiltersStmt                *sql.Stmt
	countUsersWithMultiFiltersStmt           *sql.Stmt
	createDepartmentStmt                     *sql.Stmt
	createLanguageStmt                       *sql.Stmt
	createOrUpdateGoogleUserStmt             *sql.Stmt
	createTranslationStmt                    *sql.Stmt
	createTranslationReviewStmt              *sql.Stmt
	createUserStmt                           *sql.Stmt
	deleteDepartmentStmt                     *sql.Stmt
	deleteLanguageStmt                       *sql.Stmt
	deleteTranslationStmt                    *sql.Stmt
	deleteUserStmt                           *sql.Stmt
	getApprovedTranslationStmt               *sql.Stmt
	getAssignableUsersStmt                   *sql.Stmt
	getDepartmentStmt                        *sql.Stmt
	getLanguageStmt                          *sql.Stmt
	getLanguageByCodeStmt                    *sql.Stmt
	getTranslationStmt                       *sql.Stmt
	getTranslationBySourceAndTargetStmt      *sql.Stmt
	getTranslationReviewStatusStmt           *sql.Stmt
	getTranslationWithContextStmt            *sql.Stmt
	getTranslationsByContextKeyStmt          *sql.Stmt
	getTranslationsBySourceTextsStmt         *sql.Stmt
	getUserStmt                              *sql.Stmt
	getUserByEmailStmt                       *sql.Stmt
	getUserEditLanguagesStmt                 *sql.Stmt
	getUserReviewLanguagesStmt               *sql.Stmt
	getUserWithEditLanguagesStmt             *sql.Stmt
	getUserWithLanguagesStmt                 *sql.Stmt
	getUsersWithLanguagePermissionsStmt      *sql.Stmt
	listActiveLanguagesStmt                  *sql.Stmt
	listAllDepartmentsStmt                   *sql.Stmt
	listDepartmentsStmt                      *sql.Stmt
	listLanguagesStmt                        *sql.Stmt
	listTranslationsStmt                     *sql.Stmt
	listTranslationsByLanguageStmt           *sql.Stmt
	listTranslationsByReviewStatusStmt       *sql.Stmt
	listTranslationsByUserStmt               *sql.Stmt
	listTranslationsWithFiltersStmt          *sql.Stmt
	listTranslationsWithMultipleFiltersStmt  *sql.Stmt
	listUniqueSourceTextsWithFiltersStmt     *sql.Stmt
	listUsersStmt                            *sql.Stmt
	listUsersWithFiltersStmt                 *sql.Stmt
	listUsersWithMultiFiltersStmt            *sql.Stmt
	removeAllUserEditLanguagesStmt           *sql.Stmt
	removeAllUserReviewLanguagesStmt         *sql.Stmt
	removeUserEditLanguageStmt               *sql.Stmt
	removeUserReviewLanguageStmt             *sql.Stmt
	searchTranslationsStmt                   *sql.Stmt
	setUserEditLanguagesStmt                 *sql.Stmt
	setUserReviewLanguagesStmt               *sql.Stmt
	updateDepartmentStmt                     *sql.Stmt
	updateLanguageStmt                       *sql.Stmt
	updateLastLoginStmt                      *sql.Stmt
	updateTranslationStmt                    *sql.Stmt
	updateTranslationContextStmt             *sql.Stmt
	updateTranslationReviewStatusStmt        *sql.Stmt
	updateUserStmt                           *sql.Stmt
	updateUserPasswordStmt                   *sql.Stmt
	upsertTranslationStmt                    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                       tx,
		tx:                                       tx,
		addUserEditLanguageStmt:                  q.addUserEditLanguageStmt,
		addUserReviewLanguageStmt:                q.addUserReviewLanguageStmt,
		checkAccountExistsStmt:                   q.checkAccountExistsStmt,
		countActiveLanguagesStmt:                 q.countActiveLanguagesStmt,
		countAllTranslationsStmt:                 q.countAllTranslationsStmt,
		countLanguagesStmt:                       q.countLanguagesStmt,
		countTranslationsByLanguageStmt:          q.countTranslationsByLanguageStmt,
		countTranslationsByReviewStatusStmt:      q.countTranslationsByReviewStatusStmt,
		countTranslationsBySearchStmt:            q.countTranslationsBySearchStmt,
		countTranslationsByUserStmt:              q.countTranslationsByUserStmt,
		countTranslationsWithFiltersStmt:         q.countTranslationsWithFiltersStmt,
		countTranslationsWithMultipleFiltersStmt: q.countTranslationsWithMultipleFiltersStmt,
		countUniqueSourceTextsWithFiltersStmt:    q.countUniqueSourceTextsWithFiltersStmt,
		countUsersStmt:                           q.countUsersStmt,
		countUsersByDepartmentStmt:               q.countUsersByDepartmentStmt,
		countUsersWithFiltersStmt:                q.countUsersWithFiltersStmt,
		countUsersWithMultiFiltersStmt:           q.countUsersWithMultiFiltersStmt,
		createDepartmentStmt:                     q.createDepartmentStmt,
		createLanguageStmt:                       q.createLanguageStmt,
		createOrUpdateGoogleUserStmt:             q.createOrUpdateGoogleUserStmt,
		createTranslationStmt:                    q.createTranslationStmt,
		createTranslationReviewStmt:              q.createTranslationReviewStmt,
		createUserStmt:                           q.createUserStmt,
		deleteDepartmentStmt:                     q.deleteDepartmentStmt,
		deleteLanguageStmt:                       q.deleteLanguageStmt,
		deleteTranslationStmt:                    q.deleteTranslationStmt,
		deleteUserStmt:                           q.deleteUserStmt,
		getApprovedTranslationStmt:               q.getApprovedTranslationStmt,
		getAssignableUsersStmt:                   q.getAssignableUsersStmt,
		getDepartmentStmt:                        q.getDepartmentStmt,
		getLanguageStmt:                          q.getLanguageStmt,
		getLanguageByCodeStmt:                    q.getLanguageByCodeStmt,
		getTranslationStmt:                       q.getTranslationStmt,
		getTranslationBySourceAndTargetStmt:      q.getTranslationBySourceAndTargetStmt,
		getTranslationReviewStatusStmt:           q.getTranslationReviewStatusStmt,
		getTranslationWithContextStmt:            q.getTranslationWithContextStmt,
		getTranslationsByContextKeyStmt:          q.getTranslationsByContextKeyStmt,
		getTranslationsBySourceTextsStmt:         q.getTranslationsBySourceTextsStmt,
		getUserStmt:                              q.getUserStmt,
		getUserByEmailStmt:                       q.getUserByEmailStmt,
		getUserEditLanguagesStmt:                 q.getUserEditLanguagesStmt,
		getUserReviewLanguagesStmt:               q.getUserReviewLanguagesStmt,
		getUserWithEditLanguagesStmt:             q.getUserWithEditLanguagesStmt,
		getUserWithLanguagesStmt:                 q.getUserWithLanguagesStmt,
		getUsersWithLanguagePermissionsStmt:      q.getUsersWithLanguagePermissionsStmt,
		listActiveLanguagesStmt:                  q.listActiveLanguagesStmt,
		listAllDepartmentsStmt:                   q.listAllDepartmentsStmt,
		listDepartmentsStmt:                      q.listDepartmentsStmt,
		listLanguagesStmt:                        q.listLanguagesStmt,
		listTranslationsStmt:                     q.listTranslationsStmt,
		listTranslationsByLanguageStmt:           q.listTranslationsByLanguageStmt,
		listTranslationsByReviewStatusStmt:       q.listTranslationsByReviewStatusStmt,
		listTranslationsByUserStmt:               q.listTranslationsByUserStmt,
		listTranslationsWithFiltersStmt:          q.listTranslationsWithFiltersStmt,
		listTranslationsWithMultipleFiltersStmt:  q.listTranslationsWithMultipleFiltersStmt,
		listUniqueSourceTextsWithFiltersStmt:     q.listUniqueSourceTextsWithFiltersStmt,
		listUsersStmt:                            q.listUsersStmt,
		listUsersWithFiltersStmt:                 q.listUsersWithFiltersStmt,
		listUsersWithMultiFiltersStmt:            q.listUsersWithMultiFiltersStmt,
		removeAllUserEditLanguagesStmt:           q.removeAllUserEditLanguagesStmt,
		removeAllUserReviewLanguagesStmt:         q.removeAllUserReviewLanguagesStmt,
		removeUserEditLanguageStmt:               q.removeUserEditLanguageStmt,
		removeUserReviewLanguageStmt:             q.removeUserReviewLanguageStmt,
		searchTranslationsStmt:                   q.searchTranslationsStmt,
		setUserEditLanguagesStmt:                 q.setUserEditLanguagesStmt,
		setUserReviewLanguagesStmt:               q.setUserReviewLanguagesStmt,
		updateDepartmentStmt:                     q.updateDepartmentStmt,
		updateLanguageStmt:                       q.updateLanguageStmt,
		updateLastLoginStmt:                      q.updateLastLoginStmt,
		updateTranslationStmt:                    q.updateTranslationStmt,
		updateTranslationContextStmt:             q.updateTranslationContextStmt,
		updateTranslationReviewStatusStmt:        q.updateTranslationReviewStatusStmt,
		updateUserStmt:                           q.updateUserStmt,
		updateUserPasswordStmt:                   q.updateUserPasswordStmt,
		upsertTranslationStmt:                    q.upsertTranslationStmt,
	}
}
