// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: departments.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUsersByDepartment = `-- name: CountUsersByDepartment :one
SELECT COUNT(*) FROM users
WHERE department_id = $1
`

func (q *Queries) CountUsersByDepartment(ctx context.Context, departmentID uuid.UUID) (int64, error) {
	row := q.queryRow(ctx, q.countUsersByDepartmentStmt, countUsersByDepartment, departmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
  name,
  code,
  description,
  is_active
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, code, description, is_active, created_at, updated_at
`

type CreateDepartmentParams struct {
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.queryRow(ctx, q.createDepartmentStmt, createDepartment,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.IsActive,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments
WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteDepartmentStmt, deleteDepartment, id)
	return err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, code, description, is_active, created_at, updated_at FROM departments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.queryRow(ctx, q.getDepartmentStmt, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllDepartments = `-- name: ListAllDepartments :many
SELECT id, name, code, description, is_active, created_at, updated_at FROM departments
ORDER BY name COLLATE "ko-KR-x-icu"
`

func (q *Queries) ListAllDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.query(ctx, q.listAllDepartmentsStmt, listAllDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, code, description, is_active, created_at, updated_at FROM departments
WHERE is_active = true
ORDER BY name COLLATE "ko-KR-x-icu"
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.query(ctx, q.listDepartmentsStmt, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET
  name = $2,
  code = $3,
  description = $4,
  is_active = $5,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, code, description, is_active, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.queryRow(ctx, q.updateDepartmentStmt, updateDepartment,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.IsActive,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
