// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: languages.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countActiveLanguages = `-- name: CountActiveLanguages :one
SELECT COUNT(*) FROM languages WHERE is_active = true
`

func (q *Queries) CountActiveLanguages(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countActiveLanguagesStmt, countActiveLanguages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLanguages = `-- name: CountLanguages :one
SELECT COUNT(*) FROM languages
`

func (q *Queries) CountLanguages(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countLanguagesStmt, countLanguages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (
    code,
    name,
    native_name,
    is_active
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, code, name, native_name, is_active, created_at, updated_at
`

type CreateLanguageParams struct {
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	NativeName sql.NullString `json:"native_name"`
	IsActive   sql.NullBool   `json:"is_active"`
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.queryRow(ctx, q.createLanguageStmt, createLanguage,
		arg.Code,
		arg.Name,
		arg.NativeName,
		arg.IsActive,
	)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NativeName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLanguage = `-- name: DeleteLanguage :exec
DELETE FROM languages WHERE id = $1
`

func (q *Queries) DeleteLanguage(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteLanguageStmt, deleteLanguage, id)
	return err
}

const getLanguage = `-- name: GetLanguage :one

SELECT 
    id,
    code,
    name,
    native_name,
    is_active,
    created_at,
    updated_at
FROM languages
WHERE id = $1
`

// ====================================
// Language Management SQL Queries
// ====================================
func (q *Queries) GetLanguage(ctx context.Context, id uuid.UUID) (Language, error) {
	row := q.queryRow(ctx, q.getLanguageStmt, getLanguage, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NativeName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLanguageByCode = `-- name: GetLanguageByCode :one
SELECT 
    id,
    code,
    name,
    native_name,
    is_active,
    created_at,
    updated_at
FROM languages
WHERE code = $1
`

func (q *Queries) GetLanguageByCode(ctx context.Context, code string) (Language, error) {
	row := q.queryRow(ctx, q.getLanguageByCodeStmt, getLanguageByCode, code)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NativeName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveLanguages = `-- name: ListActiveLanguages :many
SELECT 
    id,
    code,
    name,
    native_name,
    is_active,
    created_at,
    updated_at
FROM languages
WHERE is_active = true
ORDER BY name ASC
`

func (q *Queries) ListActiveLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.query(ctx, q.listActiveLanguagesStmt, listActiveLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.NativeName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguages = `-- name: ListLanguages :many
SELECT 
    id,
    code,
    name,
    native_name,
    is_active,
    created_at,
    updated_at
FROM languages
ORDER BY name ASC
`

func (q *Queries) ListLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.query(ctx, q.listLanguagesStmt, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.NativeName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLanguage = `-- name: UpdateLanguage :one
UPDATE languages 
SET 
    code = $2,
    name = $3,
    native_name = $4,
    is_active = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, code, name, native_name, is_active, created_at, updated_at
`

type UpdateLanguageParams struct {
	ID         uuid.UUID      `json:"id"`
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	NativeName sql.NullString `json:"native_name"`
	IsActive   sql.NullBool   `json:"is_active"`
}

func (q *Queries) UpdateLanguage(ctx context.Context, arg UpdateLanguageParams) (Language, error) {
	row := q.queryRow(ctx, q.updateLanguageStmt, updateLanguage,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.NativeName,
		arg.IsActive,
	)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NativeName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
