// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: translation_data.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countAllTranslations = `-- name: CountAllTranslations :one
SELECT COUNT(*) as count
FROM translation_data
`

func (q *Queries) CountAllTranslations(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countAllTranslationsStmt, countAllTranslations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTranslationsByLanguage = `-- name: CountTranslationsByLanguage :one
SELECT COUNT(*) as count
FROM translation_data
WHERE target_language = $1
`

func (q *Queries) CountTranslationsByLanguage(ctx context.Context, targetLanguage string) (int64, error) {
	row := q.queryRow(ctx, q.countTranslationsByLanguageStmt, countTranslationsByLanguage, targetLanguage)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTranslationsByReviewStatus = `-- name: CountTranslationsByReviewStatus :one
SELECT COUNT(*) as count
FROM translation_data td
INNER JOIN translation_reviews tr ON td.id = tr.translation_id
WHERE tr.review_status = $1
`

func (q *Queries) CountTranslationsByReviewStatus(ctx context.Context, reviewStatus NullReviewStatusEnum) (int64, error) {
	row := q.queryRow(ctx, q.countTranslationsByReviewStatusStmt, countTranslationsByReviewStatus, reviewStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTranslationsBySearch = `-- name: CountTranslationsBySearch :one
SELECT COUNT(*) as count
FROM translation_data
WHERE source_text ILIKE '%' || $1 || '%' 
   OR translated_text ILIKE '%' || $1 || '%'
`

func (q *Queries) CountTranslationsBySearch(ctx context.Context, dollar_1 sql.NullString) (int64, error) {
	row := q.queryRow(ctx, q.countTranslationsBySearchStmt, countTranslationsBySearch, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTranslationsByUser = `-- name: CountTranslationsByUser :one
SELECT COUNT(*) as count
FROM translation_data
WHERE created_by = $1
`

func (q *Queries) CountTranslationsByUser(ctx context.Context, createdBy uuid.NullUUID) (int64, error) {
	row := q.queryRow(ctx, q.countTranslationsByUserStmt, countTranslationsByUser, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTranslationsWithFilters = `-- name: CountTranslationsWithFilters :one
SELECT COUNT(DISTINCT td.id) as count
FROM translation_data td
LEFT JOIN translation_reviews tr ON td.id = tr.translation_id
WHERE 
    ($1::text IS NULL OR td.source_text ILIKE '%' || $1 || '%' OR td.translated_text ILIKE '%' || $1 || '%')
    AND ($2::text IS NULL OR td.target_language = $2)
    AND ($3::text IS NULL OR td.translation_engine = $3)
    AND ($4::review_status_enum IS NULL OR tr.review_status = $4)
`

type CountTranslationsWithFiltersParams struct {
	Column1 string           `json:"column_1"`
	Column2 string           `json:"column_2"`
	Column3 string           `json:"column_3"`
	Column4 ReviewStatusEnum `json:"column_4"`
}

func (q *Queries) CountTranslationsWithFilters(ctx context.Context, arg CountTranslationsWithFiltersParams) (int64, error) {
	row := q.queryRow(ctx, q.countTranslationsWithFiltersStmt, countTranslationsWithFilters,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTranslationsWithMultipleFilters = `-- name: CountTranslationsWithMultipleFilters :one
SELECT COUNT(DISTINCT td.id) as count
FROM translation_data td
LEFT JOIN translation_reviews tr ON td.id = tr.translation_id
WHERE 
    ($1::text IS NULL OR $1 = '' OR td.source_text ILIKE '%' || $1 || '%' OR td.translated_text ILIKE '%' || $1 || '%')
    AND ($2::text IS NULL OR $2 = '' OR td.target_language = ANY(string_to_array($2, ',')))
    AND ($3::text IS NULL OR $3 = '' OR td.translation_engine = ANY(string_to_array($3, ',')))
    AND ($4::text IS NULL OR $4 = '' OR tr.review_status::text = ANY(string_to_array($4, ',')))
`

type CountTranslationsWithMultipleFiltersParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
}

func (q *Queries) CountTranslationsWithMultipleFilters(ctx context.Context, arg CountTranslationsWithMultipleFiltersParams) (int64, error) {
	row := q.queryRow(ctx, q.countTranslationsWithMultipleFiltersStmt, countTranslationsWithMultipleFilters,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUniqueSourceTextsWithFilters = `-- name: CountUniqueSourceTextsWithFilters :one
SELECT COUNT(DISTINCT source_text) as count
FROM translation_data td
LEFT JOIN translation_reviews tr ON td.id = tr.translation_id
WHERE 
    ($1::text IS NULL OR $1 = '' OR td.source_text ILIKE '%' || $1 || '%' OR td.translated_text ILIKE '%' || $1 || '%')
    AND ($2::text IS NULL OR $2 = '' OR td.target_language = ANY(string_to_array($2, ',')))
    AND ($3::text IS NULL OR $3 = '' OR td.translation_engine = ANY(string_to_array($3, ',')))
    AND ($4::text IS NULL OR $4 = '' OR tr.review_status::text = ANY(string_to_array($4, ',')))
`

type CountUniqueSourceTextsWithFiltersParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
}

func (q *Queries) CountUniqueSourceTextsWithFilters(ctx context.Context, arg CountUniqueSourceTextsWithFiltersParams) (int64, error) {
	row := q.queryRow(ctx, q.countUniqueSourceTextsWithFiltersStmt, countUniqueSourceTextsWithFilters,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTranslation = `-- name: CreateTranslation :one
INSERT INTO translation_data (
    source_text, target_language, translated_text, translation_engine, 
    redis_key, element_context, quality_confidence_score, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, source_text, target_language, translated_text, translation_engine, 
          redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
`

type CreateTranslationParams struct {
	SourceText             string                `json:"source_text"`
	TargetLanguage         string                `json:"target_language"`
	TranslatedText         string                `json:"translated_text"`
	TranslationEngine      sql.NullString        `json:"translation_engine"`
	RedisKey               sql.NullString        `json:"redis_key"`
	ElementContext         pqtype.NullRawMessage `json:"element_context"`
	QualityConfidenceScore sql.NullInt32         `json:"quality_confidence_score"`
	CreatedBy              uuid.NullUUID         `json:"created_by"`
}

func (q *Queries) CreateTranslation(ctx context.Context, arg CreateTranslationParams) (TranslationDatum, error) {
	row := q.queryRow(ctx, q.createTranslationStmt, createTranslation,
		arg.SourceText,
		arg.TargetLanguage,
		arg.TranslatedText,
		arg.TranslationEngine,
		arg.RedisKey,
		arg.ElementContext,
		arg.QualityConfidenceScore,
		arg.CreatedBy,
	)
	var i TranslationDatum
	err := row.Scan(
		&i.ID,
		&i.SourceText,
		&i.TargetLanguage,
		&i.TranslatedText,
		&i.TranslationEngine,
		&i.RedisKey,
		&i.ElementContext,
		&i.QualityConfidenceScore,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTranslationReview = `-- name: CreateTranslationReview :exec
INSERT INTO translation_reviews (
    translation_id, review_status, priority
) VALUES ($1, $2, $3)
ON CONFLICT (translation_id) DO NOTHING
`

type CreateTranslationReviewParams struct {
	TranslationID uuid.UUID            `json:"translation_id"`
	ReviewStatus  NullReviewStatusEnum `json:"review_status"`
	Priority      sql.NullInt32        `json:"priority"`
}

func (q *Queries) CreateTranslationReview(ctx context.Context, arg CreateTranslationReviewParams) error {
	_, err := q.exec(ctx, q.createTranslationReviewStmt, createTranslationReview, arg.TranslationID, arg.ReviewStatus, arg.Priority)
	return err
}

const deleteTranslation = `-- name: DeleteTranslation :exec
DELETE FROM translation_data
WHERE id = $1
`

func (q *Queries) DeleteTranslation(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteTranslationStmt, deleteTranslation, id)
	return err
}

const getApprovedTranslation = `-- name: GetApprovedTranslation :one
SELECT td.translated_text, td.element_context
FROM translation_data td
JOIN translation_reviews tr ON td.id = tr.translation_id
WHERE td.source_text = $1
AND td.target_language = $2
AND tr.review_status = 'approved'
LIMIT 1
`

type GetApprovedTranslationParams struct {
	SourceText     string `json:"source_text"`
	TargetLanguage string `json:"target_language"`
}

type GetApprovedTranslationRow struct {
	TranslatedText string                `json:"translated_text"`
	ElementContext pqtype.NullRawMessage `json:"element_context"`
}

func (q *Queries) GetApprovedTranslation(ctx context.Context, arg GetApprovedTranslationParams) (GetApprovedTranslationRow, error) {
	row := q.queryRow(ctx, q.getApprovedTranslationStmt, getApprovedTranslation, arg.SourceText, arg.TargetLanguage)
	var i GetApprovedTranslationRow
	err := row.Scan(&i.TranslatedText, &i.ElementContext)
	return i, err
}

const getTranslation = `-- name: GetTranslation :one
SELECT id, source_text, target_language, translated_text, translation_engine, 
       redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
FROM translation_data
WHERE id = $1
`

func (q *Queries) GetTranslation(ctx context.Context, id uuid.UUID) (TranslationDatum, error) {
	row := q.queryRow(ctx, q.getTranslationStmt, getTranslation, id)
	var i TranslationDatum
	err := row.Scan(
		&i.ID,
		&i.SourceText,
		&i.TargetLanguage,
		&i.TranslatedText,
		&i.TranslationEngine,
		&i.RedisKey,
		&i.ElementContext,
		&i.QualityConfidenceScore,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranslationBySourceAndTarget = `-- name: GetTranslationBySourceAndTarget :one
SELECT id, source_text, target_language, translated_text, translation_engine, 
       redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
FROM translation_data
WHERE source_text = $1 AND target_language = $2
LIMIT 1
`

type GetTranslationBySourceAndTargetParams struct {
	SourceText     string `json:"source_text"`
	TargetLanguage string `json:"target_language"`
}

func (q *Queries) GetTranslationBySourceAndTarget(ctx context.Context, arg GetTranslationBySourceAndTargetParams) (TranslationDatum, error) {
	row := q.queryRow(ctx, q.getTranslationBySourceAndTargetStmt, getTranslationBySourceAndTarget, arg.SourceText, arg.TargetLanguage)
	var i TranslationDatum
	err := row.Scan(
		&i.ID,
		&i.SourceText,
		&i.TargetLanguage,
		&i.TranslatedText,
		&i.TranslationEngine,
		&i.RedisKey,
		&i.ElementContext,
		&i.QualityConfidenceScore,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranslationReviewStatus = `-- name: GetTranslationReviewStatus :one
SELECT review_status
FROM translation_reviews
WHERE translation_id = $1
`

func (q *Queries) GetTranslationReviewStatus(ctx context.Context, translationID uuid.UUID) (NullReviewStatusEnum, error) {
	row := q.queryRow(ctx, q.getTranslationReviewStatusStmt, getTranslationReviewStatus, translationID)
	var review_status NullReviewStatusEnum
	err := row.Scan(&review_status)
	return review_status, err
}

const getTranslationWithContext = `-- name: GetTranslationWithContext :many
SELECT id, source_text, target_language, translated_text, translation_engine, 
       redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
FROM translation_data
WHERE element_context @> $1::jsonb
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTranslationWithContextParams struct {
	Column1 json.RawMessage `json:"column_1"`
	Limit   int32           `json:"limit"`
	Offset  int32           `json:"offset"`
}

func (q *Queries) GetTranslationWithContext(ctx context.Context, arg GetTranslationWithContextParams) ([]TranslationDatum, error) {
	rows, err := q.query(ctx, q.getTranslationWithContextStmt, getTranslationWithContext, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationDatum
	for rows.Next() {
		var i TranslationDatum
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetLanguage,
			&i.TranslatedText,
			&i.TranslationEngine,
			&i.RedisKey,
			&i.ElementContext,
			&i.QualityConfidenceScore,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranslationsByContextKey = `-- name: GetTranslationsByContextKey :many
SELECT id, source_text, target_language, translated_text, translation_engine, 
       redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
FROM translation_data
WHERE element_context->>'page' = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTranslationsByContextKeyParams struct {
	ElementContext pqtype.NullRawMessage `json:"element_context"`
	Limit          int32                 `json:"limit"`
	Offset         int32                 `json:"offset"`
}

func (q *Queries) GetTranslationsByContextKey(ctx context.Context, arg GetTranslationsByContextKeyParams) ([]TranslationDatum, error) {
	rows, err := q.query(ctx, q.getTranslationsByContextKeyStmt, getTranslationsByContextKey, arg.ElementContext, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationDatum
	for rows.Next() {
		var i TranslationDatum
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetLanguage,
			&i.TranslatedText,
			&i.TranslationEngine,
			&i.RedisKey,
			&i.ElementContext,
			&i.QualityConfidenceScore,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranslationsBySourceTexts = `-- name: GetTranslationsBySourceTexts :many
SELECT DISTINCT
    td.id, td.source_text, td.target_language, td.translated_text, 
    td.translation_engine, td.redis_key, td.element_context, 
    td.quality_confidence_score, td.created_by, td.created_at, td.updated_at,
    COALESCE(tr.review_status::text, 'pending') as review_status
FROM translation_data td
LEFT JOIN translation_reviews tr ON td.id = tr.translation_id
WHERE td.source_text = ANY($1::text[])
ORDER BY td.source_text, td.target_language
`

type GetTranslationsBySourceTextsRow struct {
	ID                     uuid.UUID             `json:"id"`
	SourceText             string                `json:"source_text"`
	TargetLanguage         string                `json:"target_language"`
	TranslatedText         string                `json:"translated_text"`
	TranslationEngine      sql.NullString        `json:"translation_engine"`
	RedisKey               sql.NullString        `json:"redis_key"`
	ElementContext         pqtype.NullRawMessage `json:"element_context"`
	QualityConfidenceScore sql.NullInt32         `json:"quality_confidence_score"`
	CreatedBy              uuid.NullUUID         `json:"created_by"`
	CreatedAt              sql.NullTime          `json:"created_at"`
	UpdatedAt              sql.NullTime          `json:"updated_at"`
	ReviewStatus           interface{}           `json:"review_status"`
}

func (q *Queries) GetTranslationsBySourceTexts(ctx context.Context, dollar_1 []string) ([]GetTranslationsBySourceTextsRow, error) {
	rows, err := q.query(ctx, q.getTranslationsBySourceTextsStmt, getTranslationsBySourceTexts, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTranslationsBySourceTextsRow
	for rows.Next() {
		var i GetTranslationsBySourceTextsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetLanguage,
			&i.TranslatedText,
			&i.TranslationEngine,
			&i.RedisKey,
			&i.ElementContext,
			&i.QualityConfidenceScore,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslations = `-- name: ListTranslations :many
SELECT id, source_text, target_language, translated_text, translation_engine, 
       redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
FROM translation_data
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTranslationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTranslations(ctx context.Context, arg ListTranslationsParams) ([]TranslationDatum, error) {
	rows, err := q.query(ctx, q.listTranslationsStmt, listTranslations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationDatum
	for rows.Next() {
		var i TranslationDatum
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetLanguage,
			&i.TranslatedText,
			&i.TranslationEngine,
			&i.RedisKey,
			&i.ElementContext,
			&i.QualityConfidenceScore,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsByLanguage = `-- name: ListTranslationsByLanguage :many
SELECT id, source_text, target_language, translated_text, translation_engine, 
       redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
FROM translation_data
WHERE target_language = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTranslationsByLanguageParams struct {
	TargetLanguage string `json:"target_language"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListTranslationsByLanguage(ctx context.Context, arg ListTranslationsByLanguageParams) ([]TranslationDatum, error) {
	rows, err := q.query(ctx, q.listTranslationsByLanguageStmt, listTranslationsByLanguage, arg.TargetLanguage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationDatum
	for rows.Next() {
		var i TranslationDatum
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetLanguage,
			&i.TranslatedText,
			&i.TranslationEngine,
			&i.RedisKey,
			&i.ElementContext,
			&i.QualityConfidenceScore,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsByReviewStatus = `-- name: ListTranslationsByReviewStatus :many
SELECT 
    td.id, td.source_text, td.target_language, td.translated_text, 
    td.translation_engine, td.redis_key, td.element_context, 
    td.quality_confidence_score, td.created_by, td.created_at, td.updated_at
FROM translation_data td
INNER JOIN translation_reviews tr ON td.id = tr.translation_id
WHERE tr.review_status = $1
ORDER BY td.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTranslationsByReviewStatusParams struct {
	ReviewStatus NullReviewStatusEnum `json:"review_status"`
	Limit        int32                `json:"limit"`
	Offset       int32                `json:"offset"`
}

func (q *Queries) ListTranslationsByReviewStatus(ctx context.Context, arg ListTranslationsByReviewStatusParams) ([]TranslationDatum, error) {
	rows, err := q.query(ctx, q.listTranslationsByReviewStatusStmt, listTranslationsByReviewStatus, arg.ReviewStatus, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationDatum
	for rows.Next() {
		var i TranslationDatum
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetLanguage,
			&i.TranslatedText,
			&i.TranslationEngine,
			&i.RedisKey,
			&i.ElementContext,
			&i.QualityConfidenceScore,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsByUser = `-- name: ListTranslationsByUser :many
SELECT id, source_text, target_language, translated_text, translation_engine, 
       redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
FROM translation_data
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTranslationsByUserParams struct {
	CreatedBy uuid.NullUUID `json:"created_by"`
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
}

func (q *Queries) ListTranslationsByUser(ctx context.Context, arg ListTranslationsByUserParams) ([]TranslationDatum, error) {
	rows, err := q.query(ctx, q.listTranslationsByUserStmt, listTranslationsByUser, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationDatum
	for rows.Next() {
		var i TranslationDatum
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetLanguage,
			&i.TranslatedText,
			&i.TranslationEngine,
			&i.RedisKey,
			&i.ElementContext,
			&i.QualityConfidenceScore,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsWithFilters = `-- name: ListTranslationsWithFilters :many
SELECT DISTINCT
    td.id, td.source_text, td.target_language, td.translated_text, 
    td.translation_engine, td.redis_key, td.element_context, 
    td.quality_confidence_score, td.created_by, td.created_at, td.updated_at
FROM translation_data td
LEFT JOIN translation_reviews tr ON td.id = tr.translation_id
WHERE 
    ($1::text IS NULL OR td.source_text ILIKE '%' || $1 || '%' OR td.translated_text ILIKE '%' || $1 || '%')
    AND ($2::text IS NULL OR td.target_language = $2)
    AND ($3::text IS NULL OR td.translation_engine = $3)
    AND ($4::review_status_enum IS NULL OR tr.review_status = $4)
ORDER BY td.created_at DESC
LIMIT $5 OFFSET $6
`

type ListTranslationsWithFiltersParams struct {
	Column1 string           `json:"column_1"`
	Column2 string           `json:"column_2"`
	Column3 string           `json:"column_3"`
	Column4 ReviewStatusEnum `json:"column_4"`
	Limit   int32            `json:"limit"`
	Offset  int32            `json:"offset"`
}

func (q *Queries) ListTranslationsWithFilters(ctx context.Context, arg ListTranslationsWithFiltersParams) ([]TranslationDatum, error) {
	rows, err := q.query(ctx, q.listTranslationsWithFiltersStmt, listTranslationsWithFilters,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationDatum
	for rows.Next() {
		var i TranslationDatum
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetLanguage,
			&i.TranslatedText,
			&i.TranslationEngine,
			&i.RedisKey,
			&i.ElementContext,
			&i.QualityConfidenceScore,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsWithMultipleFilters = `-- name: ListTranslationsWithMultipleFilters :many
SELECT DISTINCT
    td.id, td.source_text, td.target_language, td.translated_text, 
    td.translation_engine, td.redis_key, td.element_context, 
    td.quality_confidence_score, td.created_by, td.created_at, td.updated_at
FROM translation_data td
LEFT JOIN translation_reviews tr ON td.id = tr.translation_id
WHERE 
    ($1::text IS NULL OR $1 = '' OR td.source_text ILIKE '%' || $1 || '%' OR td.translated_text ILIKE '%' || $1 || '%')
    AND ($2::text IS NULL OR $2 = '' OR td.target_language = ANY(string_to_array($2, ',')))
    AND ($3::text IS NULL OR $3 = '' OR td.translation_engine = ANY(string_to_array($3, ',')))
    AND ($4::text IS NULL OR $4 = '' OR tr.review_status::text = ANY(string_to_array($4, ',')))
ORDER BY td.created_at DESC
LIMIT $5 OFFSET $6
`

type ListTranslationsWithMultipleFiltersParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListTranslationsWithMultipleFilters(ctx context.Context, arg ListTranslationsWithMultipleFiltersParams) ([]TranslationDatum, error) {
	rows, err := q.query(ctx, q.listTranslationsWithMultipleFiltersStmt, listTranslationsWithMultipleFilters,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationDatum
	for rows.Next() {
		var i TranslationDatum
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetLanguage,
			&i.TranslatedText,
			&i.TranslationEngine,
			&i.RedisKey,
			&i.ElementContext,
			&i.QualityConfidenceScore,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueSourceTextsWithFilters = `-- name: ListUniqueSourceTextsWithFilters :many
SELECT DISTINCT ON (td.source_text)
    td.source_text,
    MAX(td.created_at) as latest_created_at
FROM translation_data td
LEFT JOIN translation_reviews tr ON td.id = tr.translation_id
WHERE 
    ($1::text IS NULL OR $1 = '' OR td.source_text ILIKE '%' || $1 || '%' OR td.translated_text ILIKE '%' || $1 || '%')
    AND ($2::text IS NULL OR $2 = '' OR td.target_language = ANY(string_to_array($2, ',')))
    AND ($3::text IS NULL OR $3 = '' OR td.translation_engine = ANY(string_to_array($3, ',')))
    AND ($4::text IS NULL OR $4 = '' OR tr.review_status::text = ANY(string_to_array($4, ',')))
GROUP BY td.source_text
ORDER BY td.source_text, latest_created_at DESC
LIMIT $5 OFFSET $6
`

type ListUniqueSourceTextsWithFiltersParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListUniqueSourceTextsWithFiltersRow struct {
	SourceText      string      `json:"source_text"`
	LatestCreatedAt interface{} `json:"latest_created_at"`
}

func (q *Queries) ListUniqueSourceTextsWithFilters(ctx context.Context, arg ListUniqueSourceTextsWithFiltersParams) ([]ListUniqueSourceTextsWithFiltersRow, error) {
	rows, err := q.query(ctx, q.listUniqueSourceTextsWithFiltersStmt, listUniqueSourceTextsWithFilters,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUniqueSourceTextsWithFiltersRow
	for rows.Next() {
		var i ListUniqueSourceTextsWithFiltersRow
		if err := rows.Scan(&i.SourceText, &i.LatestCreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTranslations = `-- name: SearchTranslations :many
SELECT id, source_text, target_language, translated_text, translation_engine, 
       redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
FROM translation_data
WHERE source_text ILIKE '%' || $1 || '%' 
   OR translated_text ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchTranslationsParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchTranslations(ctx context.Context, arg SearchTranslationsParams) ([]TranslationDatum, error) {
	rows, err := q.query(ctx, q.searchTranslationsStmt, searchTranslations, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationDatum
	for rows.Next() {
		var i TranslationDatum
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetLanguage,
			&i.TranslatedText,
			&i.TranslationEngine,
			&i.RedisKey,
			&i.ElementContext,
			&i.QualityConfidenceScore,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTranslation = `-- name: UpdateTranslation :one
UPDATE translation_data
SET translated_text = $2,
    translation_engine = $3,
    element_context = $4,
    quality_confidence_score = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, source_text, target_language, translated_text, translation_engine, 
          redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
`

type UpdateTranslationParams struct {
	ID                     uuid.UUID             `json:"id"`
	TranslatedText         string                `json:"translated_text"`
	TranslationEngine      sql.NullString        `json:"translation_engine"`
	ElementContext         pqtype.NullRawMessage `json:"element_context"`
	QualityConfidenceScore sql.NullInt32         `json:"quality_confidence_score"`
}

func (q *Queries) UpdateTranslation(ctx context.Context, arg UpdateTranslationParams) (TranslationDatum, error) {
	row := q.queryRow(ctx, q.updateTranslationStmt, updateTranslation,
		arg.ID,
		arg.TranslatedText,
		arg.TranslationEngine,
		arg.ElementContext,
		arg.QualityConfidenceScore,
	)
	var i TranslationDatum
	err := row.Scan(
		&i.ID,
		&i.SourceText,
		&i.TargetLanguage,
		&i.TranslatedText,
		&i.TranslationEngine,
		&i.RedisKey,
		&i.ElementContext,
		&i.QualityConfidenceScore,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTranslationContext = `-- name: UpdateTranslationContext :one
UPDATE translation_data
SET element_context = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, source_text, target_language, translated_text, translation_engine, 
          redis_key, element_context, quality_confidence_score, created_by, created_at, updated_at
`

type UpdateTranslationContextParams struct {
	ID             uuid.UUID             `json:"id"`
	ElementContext pqtype.NullRawMessage `json:"element_context"`
}

func (q *Queries) UpdateTranslationContext(ctx context.Context, arg UpdateTranslationContextParams) (TranslationDatum, error) {
	row := q.queryRow(ctx, q.updateTranslationContextStmt, updateTranslationContext, arg.ID, arg.ElementContext)
	var i TranslationDatum
	err := row.Scan(
		&i.ID,
		&i.SourceText,
		&i.TargetLanguage,
		&i.TranslatedText,
		&i.TranslationEngine,
		&i.RedisKey,
		&i.ElementContext,
		&i.QualityConfidenceScore,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTranslationReviewStatus = `-- name: UpdateTranslationReviewStatus :exec
UPDATE translation_reviews
SET review_status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE translation_id = $1
`

type UpdateTranslationReviewStatusParams struct {
	TranslationID uuid.UUID            `json:"translation_id"`
	ReviewStatus  NullReviewStatusEnum `json:"review_status"`
}

func (q *Queries) UpdateTranslationReviewStatus(ctx context.Context, arg UpdateTranslationReviewStatusParams) error {
	_, err := q.exec(ctx, q.updateTranslationReviewStatusStmt, updateTranslationReviewStatus, arg.TranslationID, arg.ReviewStatus)
	return err
}

const upsertTranslation = `-- name: UpsertTranslation :one
INSERT INTO translation_data (
    source_text, target_language, translated_text, 
    translation_engine, redis_key, element_context, quality_confidence_score
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (md5(source_text), target_language) 
DO UPDATE SET 
    translated_text = EXCLUDED.translated_text,
    element_context = EXCLUDED.element_context,
    quality_confidence_score = EXCLUDED.quality_confidence_score,
    updated_at = CURRENT_TIMESTAMP
RETURNING id
`

type UpsertTranslationParams struct {
	SourceText             string                `json:"source_text"`
	TargetLanguage         string                `json:"target_language"`
	TranslatedText         string                `json:"translated_text"`
	TranslationEngine      sql.NullString        `json:"translation_engine"`
	RedisKey               sql.NullString        `json:"redis_key"`
	ElementContext         pqtype.NullRawMessage `json:"element_context"`
	QualityConfidenceScore sql.NullInt32         `json:"quality_confidence_score"`
}

func (q *Queries) UpsertTranslation(ctx context.Context, arg UpsertTranslationParams) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.upsertTranslationStmt, upsertTranslation,
		arg.SourceText,
		arg.TargetLanguage,
		arg.TranslatedText,
		arg.TranslationEngine,
		arg.RedisKey,
		arg.ElementContext,
		arg.QualityConfidenceScore,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
