// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_languages.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addUserEditLanguage = `-- name: AddUserEditLanguage :exec
INSERT INTO user_edit_languages (user_id, language_id)
SELECT $1, l.id
FROM languages l
WHERE l.code = $2
ON CONFLICT (user_id, language_id) DO NOTHING
`

type AddUserEditLanguageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

func (q *Queries) AddUserEditLanguage(ctx context.Context, arg AddUserEditLanguageParams) error {
	_, err := q.exec(ctx, q.addUserEditLanguageStmt, addUserEditLanguage, arg.UserID, arg.Code)
	return err
}

const addUserReviewLanguage = `-- name: AddUserReviewLanguage :exec
INSERT INTO user_review_languages (user_id, language_id)
SELECT $1, l.id
FROM languages l
WHERE l.code = $2
ON CONFLICT (user_id, language_id) DO NOTHING
`

type AddUserReviewLanguageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

func (q *Queries) AddUserReviewLanguage(ctx context.Context, arg AddUserReviewLanguageParams) error {
	_, err := q.exec(ctx, q.addUserReviewLanguageStmt, addUserReviewLanguage, arg.UserID, arg.Code)
	return err
}

const getUserEditLanguages = `-- name: GetUserEditLanguages :many


SELECT 
    l.id,
    l.code,
    l.name,
    l.native_name,
    l.is_active
FROM user_edit_languages uel
INNER JOIN languages l ON uel.language_id = l.id
WHERE uel.user_id = $1
ORDER BY l.name
`

type GetUserEditLanguagesRow struct {
	ID         uuid.UUID      `json:"id"`
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	NativeName sql.NullString `json:"native_name"`
	IsActive   sql.NullBool   `json:"is_active"`
}

// ====================================
// User Language Permission SQL Queries
// ====================================
// ====================================
// USER EDIT LANGUAGES
// ====================================
func (q *Queries) GetUserEditLanguages(ctx context.Context, userID uuid.UUID) ([]GetUserEditLanguagesRow, error) {
	rows, err := q.query(ctx, q.getUserEditLanguagesStmt, getUserEditLanguages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserEditLanguagesRow
	for rows.Next() {
		var i GetUserEditLanguagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.NativeName,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReviewLanguages = `-- name: GetUserReviewLanguages :many

SELECT 
    l.id,
    l.code,
    l.name,
    l.native_name,
    l.is_active
FROM user_review_languages url
INNER JOIN languages l ON url.language_id = l.id
WHERE url.user_id = $1
ORDER BY l.name
`

type GetUserReviewLanguagesRow struct {
	ID         uuid.UUID      `json:"id"`
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	NativeName sql.NullString `json:"native_name"`
	IsActive   sql.NullBool   `json:"is_active"`
}

// ====================================
// USER REVIEW LANGUAGES
// ====================================
func (q *Queries) GetUserReviewLanguages(ctx context.Context, userID uuid.UUID) ([]GetUserReviewLanguagesRow, error) {
	rows, err := q.query(ctx, q.getUserReviewLanguagesStmt, getUserReviewLanguages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserReviewLanguagesRow
	for rows.Next() {
		var i GetUserReviewLanguagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.NativeName,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithLanguages = `-- name: GetUserWithLanguages :one

SELECT 
    u.id,
    u.username,
    u.email,
    u.user_role,
    u.is_active,
    u.department_id,
    u.employee_id,
    u.created_at,
    u.updated_at,
    u.last_login_at,
    d.name as department_name,
    d.code as department_code,
    COALESCE(
        ARRAY_AGG(DISTINCT el.code) FILTER (WHERE el.code IS NOT NULL), 
        ARRAY[]::text[]
    ) as edit_language_codes,
    COALESCE(
        ARRAY_AGG(DISTINCT rl.code) FILTER (WHERE rl.code IS NOT NULL), 
        ARRAY[]::text[]
    ) as review_language_codes
FROM users u
INNER JOIN departments d ON u.department_id = d.id
LEFT JOIN user_edit_languages uel ON u.id = uel.user_id
LEFT JOIN languages el ON uel.language_id = el.id
LEFT JOIN user_review_languages url ON u.id = url.user_id
LEFT JOIN languages rl ON url.language_id = rl.id
WHERE u.id = $1
GROUP BY u.id, u.username, u.email, u.user_role, u.is_active, 
         u.department_id, u.employee_id, u.created_at, u.updated_at, 
         u.last_login_at, d.name, d.code
`

type GetUserWithLanguagesRow struct {
	ID                  uuid.UUID    `json:"id"`
	Username            string       `json:"username"`
	Email               string       `json:"email"`
	UserRole            UserRoleEnum `json:"user_role"`
	IsActive            bool         `json:"is_active"`
	DepartmentID        uuid.UUID    `json:"department_id"`
	EmployeeID          string       `json:"employee_id"`
	CreatedAt           time.Time    `json:"created_at"`
	UpdatedAt           time.Time    `json:"updated_at"`
	LastLoginAt         sql.NullTime `json:"last_login_at"`
	DepartmentName      string       `json:"department_name"`
	DepartmentCode      string       `json:"department_code"`
	EditLanguageCodes   interface{}  `json:"edit_language_codes"`
	ReviewLanguageCodes interface{}  `json:"review_language_codes"`
}

// ====================================
// COMBINED QUERIES
// ====================================
func (q *Queries) GetUserWithLanguages(ctx context.Context, id uuid.UUID) (GetUserWithLanguagesRow, error) {
	row := q.queryRow(ctx, q.getUserWithLanguagesStmt, getUserWithLanguages, id)
	var i GetUserWithLanguagesRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.UserRole,
		&i.IsActive,
		&i.DepartmentID,
		&i.EmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DepartmentName,
		&i.DepartmentCode,
		&i.EditLanguageCodes,
		&i.ReviewLanguageCodes,
	)
	return i, err
}

const removeAllUserEditLanguages = `-- name: RemoveAllUserEditLanguages :exec
DELETE FROM user_edit_languages WHERE user_id = $1
`

func (q *Queries) RemoveAllUserEditLanguages(ctx context.Context, userID uuid.UUID) error {
	_, err := q.exec(ctx, q.removeAllUserEditLanguagesStmt, removeAllUserEditLanguages, userID)
	return err
}

const removeAllUserReviewLanguages = `-- name: RemoveAllUserReviewLanguages :exec
DELETE FROM user_review_languages WHERE user_id = $1
`

func (q *Queries) RemoveAllUserReviewLanguages(ctx context.Context, userID uuid.UUID) error {
	_, err := q.exec(ctx, q.removeAllUserReviewLanguagesStmt, removeAllUserReviewLanguages, userID)
	return err
}

const removeUserEditLanguage = `-- name: RemoveUserEditLanguage :exec
DELETE FROM user_edit_languages 
WHERE user_id = $1 
AND language_id = (SELECT id FROM languages WHERE code = $2)
`

type RemoveUserEditLanguageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

func (q *Queries) RemoveUserEditLanguage(ctx context.Context, arg RemoveUserEditLanguageParams) error {
	_, err := q.exec(ctx, q.removeUserEditLanguageStmt, removeUserEditLanguage, arg.UserID, arg.Code)
	return err
}

const removeUserReviewLanguage = `-- name: RemoveUserReviewLanguage :exec
DELETE FROM user_review_languages 
WHERE user_id = $1 
AND language_id = (SELECT id FROM languages WHERE code = $2)
`

type RemoveUserReviewLanguageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

func (q *Queries) RemoveUserReviewLanguage(ctx context.Context, arg RemoveUserReviewLanguageParams) error {
	_, err := q.exec(ctx, q.removeUserReviewLanguageStmt, removeUserReviewLanguage, arg.UserID, arg.Code)
	return err
}

const setUserEditLanguages = `-- name: SetUserEditLanguages :exec
DELETE FROM user_edit_languages WHERE user_id = $1
`

func (q *Queries) SetUserEditLanguages(ctx context.Context, userID uuid.UUID) error {
	_, err := q.exec(ctx, q.setUserEditLanguagesStmt, setUserEditLanguages, userID)
	return err
}

const setUserReviewLanguages = `-- name: SetUserReviewLanguages :exec
DELETE FROM user_review_languages WHERE user_id = $1
`

func (q *Queries) SetUserReviewLanguages(ctx context.Context, userID uuid.UUID) error {
	_, err := q.exec(ctx, q.setUserReviewLanguagesStmt, setUserReviewLanguages, userID)
	return err
}
