// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkAccountExists = `-- name: CheckAccountExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) CheckAccountExists(ctx context.Context, email string) (bool, error) {
	row := q.queryRow(ctx, q.checkAccountExistsStmt, checkAccountExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUsers = `-- name: CountUsers :one

SELECT COUNT(*) FROM users
`

// ====================================
// STATISTICS AND UTILITY QUERIES
// ====================================
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countUsersStmt, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithFilters = `-- name: CountUsersWithFilters :one
SELECT COUNT(*) 
FROM users u
WHERE 
    ($1::user_role_enum IS NULL OR u.user_role = $1::user_role_enum)
    AND ($2::boolean IS NULL OR u.is_active = $2::boolean)
    AND ($3::text IS NULL OR u.email ILIKE '%' || $3::text || '%' OR u.username ILIKE '%' || $3::text || '%' OR u.employee_id ILIKE '%' || $3::text || '%')
`

type CountUsersWithFiltersParams struct {
	Role     NullUserRoleEnum `json:"role"`
	IsActive sql.NullBool     `json:"is_active"`
	Search   sql.NullString   `json:"search"`
}

func (q *Queries) CountUsersWithFilters(ctx context.Context, arg CountUsersWithFiltersParams) (int64, error) {
	row := q.queryRow(ctx, q.countUsersWithFiltersStmt, countUsersWithFilters, arg.Role, arg.IsActive, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithMultiFilters = `-- name: CountUsersWithMultiFilters :one
SELECT COUNT(*) 
FROM users u
WHERE 
    (NULLIF($1, '')::text IS NULL OR u.user_role = ANY(string_to_array($1, ',')::user_role_enum[]))
    AND (NULLIF($2, '')::text IS NULL OR u.is_active = ANY(string_to_array($2, ',')::boolean[]))
    AND (NULLIF($3, '')::text IS NULL OR u.department_id = ANY(string_to_array($3, ',')::uuid[]))
    AND (NULLIF($4, '')::text IS NULL OR u.email ILIKE '%' || $4 || '%' OR u.username ILIKE '%' || $4 || '%' OR u.employee_id ILIKE '%' || $4 || '%')
`

type CountUsersWithMultiFiltersParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
}

func (q *Queries) CountUsersWithMultiFilters(ctx context.Context, arg CountUsersWithMultiFiltersParams) (int64, error) {
	row := q.queryRow(ctx, q.countUsersWithMultiFiltersStmt, countUsersWithMultiFilters,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrUpdateGoogleUser = `-- name: CreateOrUpdateGoogleUser :one
INSERT INTO users (
    username,
    email,
    user_role,
    is_active,
    department_id,
    employee_id,
    last_login_at
) VALUES (
    $1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP
)
ON CONFLICT (email) 
DO UPDATE SET
    last_login_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, username, email, user_role, is_active, department_id, employee_id, created_at, updated_at, last_login_at
`

type CreateOrUpdateGoogleUserParams struct {
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	UserRole     UserRoleEnum `json:"user_role"`
	IsActive     bool         `json:"is_active"`
	DepartmentID uuid.UUID    `json:"department_id"`
	EmployeeID   string       `json:"employee_id"`
}

type CreateOrUpdateGoogleUserRow struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	UserRole     UserRoleEnum `json:"user_role"`
	IsActive     bool         `json:"is_active"`
	DepartmentID uuid.UUID    `json:"department_id"`
	EmployeeID   string       `json:"employee_id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
}

func (q *Queries) CreateOrUpdateGoogleUser(ctx context.Context, arg CreateOrUpdateGoogleUserParams) (CreateOrUpdateGoogleUserRow, error) {
	row := q.queryRow(ctx, q.createOrUpdateGoogleUserStmt, createOrUpdateGoogleUser,
		arg.Username,
		arg.Email,
		arg.UserRole,
		arg.IsActive,
		arg.DepartmentID,
		arg.EmployeeID,
	)
	var i CreateOrUpdateGoogleUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.UserRole,
		&i.IsActive,
		&i.DepartmentID,
		&i.EmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password_hash,
    user_role,
    is_active,
    department_id,
    employee_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, username, email, user_role, is_active, department_id, employee_id, created_at, updated_at
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	UserRole     UserRoleEnum   `json:"user_role"`
	IsActive     bool           `json:"is_active"`
	DepartmentID uuid.UUID      `json:"department_id"`
	EmployeeID   string         `json:"employee_id"`
}

type CreateUserRow struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	UserRole     UserRoleEnum `json:"user_role"`
	IsActive     bool         `json:"is_active"`
	DepartmentID uuid.UUID    `json:"department_id"`
	EmployeeID   string       `json:"employee_id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.UserRole,
		arg.IsActive,
		arg.DepartmentID,
		arg.EmployeeID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.UserRole,
		&i.IsActive,
		&i.DepartmentID,
		&i.EmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	return err
}

const getAssignableUsers = `-- name: GetAssignableUsers :many
SELECT 
    u.id,
    u.username,
    u.email,
    u.user_role,
    u.is_active,
    u.department_id,
    u.employee_id,
    d.name as department_name,
    d.code as department_code
FROM users u
INNER JOIN departments d ON u.department_id = d.id
WHERE 
    u.is_active = true
    AND u.user_role IN ('admin', 'internal_reviewer', 'external_reviewer')
ORDER BY u.username
`

type GetAssignableUsersRow struct {
	ID             uuid.UUID    `json:"id"`
	Username       string       `json:"username"`
	Email          string       `json:"email"`
	UserRole       UserRoleEnum `json:"user_role"`
	IsActive       bool         `json:"is_active"`
	DepartmentID   uuid.UUID    `json:"department_id"`
	EmployeeID     string       `json:"employee_id"`
	DepartmentName string       `json:"department_name"`
	DepartmentCode string       `json:"department_code"`
}

func (q *Queries) GetAssignableUsers(ctx context.Context) ([]GetAssignableUsersRow, error) {
	rows, err := q.query(ctx, q.getAssignableUsersStmt, getAssignableUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssignableUsersRow
	for rows.Next() {
		var i GetAssignableUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.UserRole,
			&i.IsActive,
			&i.DepartmentID,
			&i.EmployeeID,
			&i.DepartmentName,
			&i.DepartmentCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one


SELECT 
    u.id,
    u.username,
    u.email,
    u.password_hash,
    u.user_role,
    u.is_active,
    u.department_id,
    u.employee_id,
    u.created_at,
    u.updated_at,
    u.last_login_at,
    d.name as department_name,
    d.code as department_code,
    COALESCE(
        (SELECT JSON_AGG(
            JSON_BUILD_OBJECT(
                'id', l.id::text,
                'code', l.code,
                'name', l.name,
                'native_name', l.native_name,
                'is_active', l.is_active
            ) ORDER BY l.name
        )
        FROM user_edit_languages uel
        INNER JOIN languages l ON uel.language_id = l.id
        WHERE uel.user_id = u.id),
        '[]'::json
    ) as edit_languages,
    COALESCE(
        (SELECT JSON_AGG(
            JSON_BUILD_OBJECT(
                'id', l.id::text,
                'code', l.code,
                'name', l.name,
                'native_name', l.native_name,
                'is_active', l.is_active
            ) ORDER BY l.name
        )
        FROM user_review_languages url
        INNER JOIN languages l ON url.language_id = l.id
        WHERE url.user_id = u.id),
        '[]'::json
    ) as review_languages
FROM users u
INNER JOIN departments d ON u.department_id = d.id
WHERE u.id = $1
`

type GetUserRow struct {
	ID              uuid.UUID      `json:"id"`
	Username        string         `json:"username"`
	Email           string         `json:"email"`
	PasswordHash    sql.NullString `json:"password_hash"`
	UserRole        UserRoleEnum   `json:"user_role"`
	IsActive        bool           `json:"is_active"`
	DepartmentID    uuid.UUID      `json:"department_id"`
	EmployeeID      string         `json:"employee_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	LastLoginAt     sql.NullTime   `json:"last_login_at"`
	DepartmentName  string         `json:"department_name"`
	DepartmentCode  string         `json:"department_code"`
	EditLanguages   interface{}    `json:"edit_languages"`
	ReviewLanguages interface{}    `json:"review_languages"`
}

// ====================================
// User Management SQL Queries
// ====================================
// ====================================
// BASIC CRUD OPERATIONS
// ====================================
func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.UserRole,
		&i.IsActive,
		&i.DepartmentID,
		&i.EmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DepartmentName,
		&i.DepartmentCode,
		&i.EditLanguages,
		&i.ReviewLanguages,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    u.id,
    u.username,
    u.email,
    u.password_hash,
    u.user_role,
    u.is_active,
    u.department_id,
    u.employee_id,
    u.created_at,
    u.updated_at,
    u.last_login_at,
    d.name as department_name,
    d.code as department_code
FROM users u
INNER JOIN departments d ON u.department_id = d.id
WHERE u.email = $1
`

type GetUserByEmailRow struct {
	ID             uuid.UUID      `json:"id"`
	Username       string         `json:"username"`
	Email          string         `json:"email"`
	PasswordHash   sql.NullString `json:"password_hash"`
	UserRole       UserRoleEnum   `json:"user_role"`
	IsActive       bool           `json:"is_active"`
	DepartmentID   uuid.UUID      `json:"department_id"`
	EmployeeID     string         `json:"employee_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	LastLoginAt    sql.NullTime   `json:"last_login_at"`
	DepartmentName string         `json:"department_name"`
	DepartmentCode string         `json:"department_code"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.UserRole,
		&i.IsActive,
		&i.DepartmentID,
		&i.EmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DepartmentName,
		&i.DepartmentCode,
	)
	return i, err
}

const getUserWithEditLanguages = `-- name: GetUserWithEditLanguages :one

SELECT 
    u.id,
    u.username,
    u.email,
    u.user_role,
    u.is_active,
    u.department_id,
    u.employee_id,
    d.name as department_name,
    ARRAY_AGG(DISTINCT l_edit.code) FILTER (WHERE l_edit.code IS NOT NULL) as edit_languages,
    ARRAY_AGG(DISTINCT l_review.code) FILTER (WHERE l_review.code IS NOT NULL) as review_languages
FROM users u
INNER JOIN departments d ON u.department_id = d.id
LEFT JOIN user_edit_languages uel ON u.id = uel.user_id
LEFT JOIN languages l_edit ON uel.language_id = l_edit.id AND l_edit.is_active = true
LEFT JOIN user_review_languages url ON u.id = url.user_id
LEFT JOIN languages l_review ON url.language_id = l_review.id AND l_review.is_active = true
WHERE u.id = $1
GROUP BY u.id, u.username, u.email, u.user_role, u.is_active, u.department_id, u.employee_id, d.name
`

type GetUserWithEditLanguagesRow struct {
	ID              uuid.UUID    `json:"id"`
	Username        string       `json:"username"`
	Email           string       `json:"email"`
	UserRole        UserRoleEnum `json:"user_role"`
	IsActive        bool         `json:"is_active"`
	DepartmentID    uuid.UUID    `json:"department_id"`
	EmployeeID      string       `json:"employee_id"`
	DepartmentName  string       `json:"department_name"`
	EditLanguages   interface{}  `json:"edit_languages"`
	ReviewLanguages interface{}  `json:"review_languages"`
}

// ====================================
// USER LANGUAGE PERMISSIONS QUERIES
// ====================================
func (q *Queries) GetUserWithEditLanguages(ctx context.Context, id uuid.UUID) (GetUserWithEditLanguagesRow, error) {
	row := q.queryRow(ctx, q.getUserWithEditLanguagesStmt, getUserWithEditLanguages, id)
	var i GetUserWithEditLanguagesRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.UserRole,
		&i.IsActive,
		&i.DepartmentID,
		&i.EmployeeID,
		&i.DepartmentName,
		&i.EditLanguages,
		&i.ReviewLanguages,
	)
	return i, err
}

const getUsersWithLanguagePermissions = `-- name: GetUsersWithLanguagePermissions :many
SELECT 
    u.id,
    u.username,
    u.email,
    u.user_role,
    u.is_active,
    u.department_id,
    u.employee_id,
    d.name as department_name,
    ARRAY_AGG(DISTINCT l_edit.code) FILTER (WHERE l_edit.code IS NOT NULL) as edit_languages,
    ARRAY_AGG(DISTINCT l_review.code) FILTER (WHERE l_review.code IS NOT NULL) as review_languages
FROM users u
INNER JOIN departments d ON u.department_id = d.id
LEFT JOIN user_edit_languages uel ON u.id = uel.user_id
LEFT JOIN languages l_edit ON uel.language_id = l_edit.id AND l_edit.is_active = true
LEFT JOIN user_review_languages url ON u.id = url.user_id
LEFT JOIN languages l_review ON url.language_id = l_review.id AND l_review.is_active = true
WHERE u.is_active = true
GROUP BY u.id, u.username, u.email, u.user_role, u.is_active, u.department_id, u.employee_id, d.name
ORDER BY u.username
LIMIT $1 OFFSET $2
`

type GetUsersWithLanguagePermissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUsersWithLanguagePermissionsRow struct {
	ID              uuid.UUID    `json:"id"`
	Username        string       `json:"username"`
	Email           string       `json:"email"`
	UserRole        UserRoleEnum `json:"user_role"`
	IsActive        bool         `json:"is_active"`
	DepartmentID    uuid.UUID    `json:"department_id"`
	EmployeeID      string       `json:"employee_id"`
	DepartmentName  string       `json:"department_name"`
	EditLanguages   interface{}  `json:"edit_languages"`
	ReviewLanguages interface{}  `json:"review_languages"`
}

func (q *Queries) GetUsersWithLanguagePermissions(ctx context.Context, arg GetUsersWithLanguagePermissionsParams) ([]GetUsersWithLanguagePermissionsRow, error) {
	rows, err := q.query(ctx, q.getUsersWithLanguagePermissionsStmt, getUsersWithLanguagePermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWithLanguagePermissionsRow
	for rows.Next() {
		var i GetUsersWithLanguagePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.UserRole,
			&i.IsActive,
			&i.DepartmentID,
			&i.EmployeeID,
			&i.DepartmentName,
			&i.EditLanguages,
			&i.ReviewLanguages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many

SELECT 
    u.id,
    u.username,
    u.email,
    u.user_role,
    u.is_active,
    u.department_id,
    u.employee_id,
    u.created_at,
    u.updated_at,
    u.last_login_at,
    d.name as department_name,
    d.code as department_code,
    COALESCE(
        (SELECT JSON_AGG(
            JSON_BUILD_OBJECT(
                'id', l.id::text,
                'code', l.code,
                'name', l.name,
                'native_name', l.native_name,
                'is_active', l.is_active
            ) ORDER BY l.name
        )
        FROM user_edit_languages uel
        INNER JOIN languages l ON uel.language_id = l.id
        WHERE uel.user_id = u.id),
        '[]'::json
    ) as edit_languages,
    COALESCE(
        (SELECT JSON_AGG(
            JSON_BUILD_OBJECT(
                'id', l.id::text,
                'code', l.code,
                'name', l.name,
                'native_name', l.native_name,
                'is_active', l.is_active
            ) ORDER BY l.name
        )
        FROM user_review_languages url
        INNER JOIN languages l ON url.language_id = l.id
        WHERE url.user_id = u.id),
        '[]'::json
    ) as review_languages
FROM users u
INNER JOIN departments d ON u.department_id = d.id
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID              uuid.UUID    `json:"id"`
	Username        string       `json:"username"`
	Email           string       `json:"email"`
	UserRole        UserRoleEnum `json:"user_role"`
	IsActive        bool         `json:"is_active"`
	DepartmentID    uuid.UUID    `json:"department_id"`
	EmployeeID      string       `json:"employee_id"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	LastLoginAt     sql.NullTime `json:"last_login_at"`
	DepartmentName  string       `json:"department_name"`
	DepartmentCode  string       `json:"department_code"`
	EditLanguages   interface{}  `json:"edit_languages"`
	ReviewLanguages interface{}  `json:"review_languages"`
}

// ====================================
// QUERY AND SEARCH OPERATIONS
// ====================================
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.UserRole,
			&i.IsActive,
			&i.DepartmentID,
			&i.EmployeeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.DepartmentName,
			&i.DepartmentCode,
			&i.EditLanguages,
			&i.ReviewLanguages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithFilters = `-- name: ListUsersWithFilters :many
WITH user_edit_langs AS (
    SELECT 
        uel.user_id,
        COALESCE(
            JSON_AGG(
                JSON_BUILD_OBJECT(
                    'id', l.id::text,
                    'code', l.code,
                    'name', l.name,
                    'native_name', l.native_name,
                    'is_active', l.is_active
                ) ORDER BY l.name
            ) FILTER (WHERE l.id IS NOT NULL),
            '[]'::json
        ) as edit_languages
    FROM users u
    LEFT JOIN user_edit_languages uel ON u.id = uel.user_id
    LEFT JOIN languages l ON uel.language_id = l.id
    GROUP BY uel.user_id
),
user_review_langs AS (
    SELECT 
        url.user_id,
        COALESCE(
            JSON_AGG(
                JSON_BUILD_OBJECT(
                    'id', l.id::text,
                    'code', l.code,
                    'name', l.name,
                    'native_name', l.native_name,
                    'is_active', l.is_active
                ) ORDER BY l.name
            ) FILTER (WHERE l.id IS NOT NULL),
            '[]'::json
        ) as review_languages
    FROM users u
    LEFT JOIN user_review_languages url ON u.id = url.user_id
    LEFT JOIN languages l ON url.language_id = l.id
    GROUP BY url.user_id
)
SELECT 
    u.id,
    u.username,
    u.email,
    u.user_role,
    u.is_active,
    u.department_id,
    u.employee_id,
    u.created_at,
    u.updated_at,
    u.last_login_at,
    d.name as department_name,
    d.code as department_code,
    COALESCE(uel.edit_languages, '[]'::json) as edit_languages,
    COALESCE(url.review_languages, '[]'::json) as review_languages
FROM users u
INNER JOIN departments d ON u.department_id = d.id
LEFT JOIN user_edit_langs uel ON u.id = uel.user_id
LEFT JOIN user_review_langs url ON u.id = url.user_id
WHERE 
    ($3::user_role_enum IS NULL OR u.user_role = $3::user_role_enum)
    AND ($4::boolean IS NULL OR u.is_active = $4::boolean)
    AND ($5::text IS NULL OR u.email ILIKE '%' || $5::text || '%' OR u.username ILIKE '%' || $5::text || '%' OR u.employee_id ILIKE '%' || $5::text || '%')
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersWithFiltersParams struct {
	Limit    int32            `json:"limit"`
	Offset   int32            `json:"offset"`
	Role     NullUserRoleEnum `json:"role"`
	IsActive sql.NullBool     `json:"is_active"`
	Search   sql.NullString   `json:"search"`
}

type ListUsersWithFiltersRow struct {
	ID              uuid.UUID    `json:"id"`
	Username        string       `json:"username"`
	Email           string       `json:"email"`
	UserRole        UserRoleEnum `json:"user_role"`
	IsActive        bool         `json:"is_active"`
	DepartmentID    uuid.UUID    `json:"department_id"`
	EmployeeID      string       `json:"employee_id"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	LastLoginAt     sql.NullTime `json:"last_login_at"`
	DepartmentName  string       `json:"department_name"`
	DepartmentCode  string       `json:"department_code"`
	EditLanguages   interface{}  `json:"edit_languages"`
	ReviewLanguages interface{}  `json:"review_languages"`
}

func (q *Queries) ListUsersWithFilters(ctx context.Context, arg ListUsersWithFiltersParams) ([]ListUsersWithFiltersRow, error) {
	rows, err := q.query(ctx, q.listUsersWithFiltersStmt, listUsersWithFilters,
		arg.Limit,
		arg.Offset,
		arg.Role,
		arg.IsActive,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithFiltersRow
	for rows.Next() {
		var i ListUsersWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.UserRole,
			&i.IsActive,
			&i.DepartmentID,
			&i.EmployeeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.DepartmentName,
			&i.DepartmentCode,
			&i.EditLanguages,
			&i.ReviewLanguages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithMultiFilters = `-- name: ListUsersWithMultiFilters :many
WITH user_edit_langs AS (
    SELECT 
        uel.user_id,
        COALESCE(
            JSON_AGG(
                JSON_BUILD_OBJECT(
                    'id', l.id::text,
                    'code', l.code,
                    'name', l.name,
                    'native_name', l.native_name,
                    'is_active', l.is_active
                ) ORDER BY l.name
            ) FILTER (WHERE l.id IS NOT NULL),
            '[]'::json
        ) as edit_languages
    FROM users u
    LEFT JOIN user_edit_languages uel ON u.id = uel.user_id
    LEFT JOIN languages l ON uel.language_id = l.id
    GROUP BY uel.user_id
),
user_review_langs AS (
    SELECT 
        url.user_id,
        COALESCE(
            JSON_AGG(
                JSON_BUILD_OBJECT(
                    'id', l.id::text,
                    'code', l.code,
                    'name', l.name,
                    'native_name', l.native_name,
                    'is_active', l.is_active
                ) ORDER BY l.name
            ) FILTER (WHERE l.id IS NOT NULL),
            '[]'::json
        ) as review_languages
    FROM users u
    LEFT JOIN user_review_languages url ON u.id = url.user_id
    LEFT JOIN languages l ON url.language_id = l.id
    GROUP BY url.user_id
)
SELECT 
    u.id,
    u.username,
    u.email,
    u.user_role,
    u.is_active,
    u.department_id,
    u.employee_id,
    u.created_at,
    u.updated_at,
    u.last_login_at,
    d.name as department_name,
    d.code as department_code,
    COALESCE(uel.edit_languages, '[]'::json) as edit_languages,
    COALESCE(url.review_languages, '[]'::json) as review_languages
FROM users u
INNER JOIN departments d ON u.department_id = d.id
LEFT JOIN user_edit_langs uel ON u.id = uel.user_id
LEFT JOIN user_review_langs url ON u.id = url.user_id
WHERE 
    (NULLIF($3, '')::text IS NULL OR u.user_role = ANY(string_to_array($3, ',')::user_role_enum[]))
    AND (NULLIF($4, '')::text IS NULL OR u.is_active = ANY(string_to_array($4, ',')::boolean[]))
    AND (NULLIF($5, '')::text IS NULL OR u.department_id = ANY(string_to_array($5, ',')::uuid[]))
    AND (NULLIF($6, '')::text IS NULL OR u.email ILIKE '%' || $6 || '%' OR u.username ILIKE '%' || $6 || '%' OR u.employee_id ILIKE '%' || $6 || '%')
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersWithMultiFiltersParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
	Column6 interface{} `json:"column_6"`
}

type ListUsersWithMultiFiltersRow struct {
	ID              uuid.UUID    `json:"id"`
	Username        string       `json:"username"`
	Email           string       `json:"email"`
	UserRole        UserRoleEnum `json:"user_role"`
	IsActive        bool         `json:"is_active"`
	DepartmentID    uuid.UUID    `json:"department_id"`
	EmployeeID      string       `json:"employee_id"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	LastLoginAt     sql.NullTime `json:"last_login_at"`
	DepartmentName  string       `json:"department_name"`
	DepartmentCode  string       `json:"department_code"`
	EditLanguages   interface{}  `json:"edit_languages"`
	ReviewLanguages interface{}  `json:"review_languages"`
}

func (q *Queries) ListUsersWithMultiFilters(ctx context.Context, arg ListUsersWithMultiFiltersParams) ([]ListUsersWithMultiFiltersRow, error) {
	rows, err := q.query(ctx, q.listUsersWithMultiFiltersStmt, listUsersWithMultiFilters,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithMultiFiltersRow
	for rows.Next() {
		var i ListUsersWithMultiFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.UserRole,
			&i.IsActive,
			&i.DepartmentID,
			&i.EmployeeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.DepartmentName,
			&i.DepartmentCode,
			&i.EditLanguages,
			&i.ReviewLanguages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec

UPDATE users 
SET 
    last_login_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// ====================================
// UPDATE LAST LOGIN
// ====================================
func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.updateLastLoginStmt, updateLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET 
    username = $2,
    email = $3,
    user_role = $4,
    is_active = $5,
    department_id = $6,
    employee_id = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, email, user_role, is_active, department_id, employee_id, created_at, updated_at
`

type UpdateUserParams struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	UserRole     UserRoleEnum `json:"user_role"`
	IsActive     bool         `json:"is_active"`
	DepartmentID uuid.UUID    `json:"department_id"`
	EmployeeID   string       `json:"employee_id"`
}

type UpdateUserRow struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	UserRole     UserRoleEnum `json:"user_role"`
	IsActive     bool         `json:"is_active"`
	DepartmentID uuid.UUID    `json:"department_id"`
	EmployeeID   string       `json:"employee_id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.UserRole,
		arg.IsActive,
		arg.DepartmentID,
		arg.EmployeeID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.UserRole,
		&i.IsActive,
		&i.DepartmentID,
		&i.EmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one

UPDATE users 
SET 
    password_hash = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, email, user_role, is_active
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID      `json:"id"`
	PasswordHash sql.NullString `json:"password_hash"`
}

type UpdateUserPasswordRow struct {
	ID       uuid.UUID    `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	UserRole UserRoleEnum `json:"user_role"`
	IsActive bool         `json:"is_active"`
}

// ====================================
// AUTHENTICATION AND PASSWORD QUERIES
// ====================================
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.queryRow(ctx, q.updateUserPasswordStmt, updateUserPassword, arg.ID, arg.PasswordHash)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.UserRole,
		&i.IsActive,
	)
	return i, err
}
