/**
 * AddLeadSheet - 리드 추가 Sheet 컴포넌트
 * CSV/XLSX 스마트 파싱 및 수동 리드 추가 기능을 제공합니다.
 */

import { useQueryClient } from "@tanstack/react-query"
import { Download, FileText, Plus, RefreshCw, Upload, X } from "lucide-react"
import { useCallback, useEffect, useId, useRef, useState } from "react"
import toast from "react-hot-toast"
import { useTranslation } from "react-i18next"
import { ColumnMappingModal } from "@/components/leads/ColumnMappingModal"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet"
import { customerGroupKeys, useCreateCustomerGroup } from "@/lib/api/hooks/customer-groups"
import { leadKeys, useCreateLead } from "@/lib/api/hooks/leads"
import { leadsApi } from "@/lib/api/services/leads"
import type { CreateCustomerGroupRequest, CustomerGroup } from "@/lib/api/types/customer-group"
import type { Lead } from "@/lib/api/types/lead"
import {
  generateCSVTemplate,
  generateXLSXTemplate,
  type LeadCSVData,
  parseCSV,
  parseXLSX,
  validateCSVData,
} from "@/lib/csv-utils"
import { analyzeCSVLeadsForGroupName } from "@/lib/utils/csv-lead-analyzer"
import { generateGroupName } from "@/lib/utils/group-name-generator"
import {
  parseCSVWithMappings,
  type SmartParseResult,
  smartAnalyzeCSV,
} from "@/lib/utils/smart-csv-parser"
import { LeadForm } from "@/pages/leads/LeadForm"

export type AddLeadSheetProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
  workspaceId: string
  customerGroups: CustomerGroup[]
  /** 현재 선택된 고객 그룹 ID (기본값으로 사용) */
  selectedCustomerGroupId?: string
  /** 리드 추가 완료 시 콜백 */
  onComplete?: (groupId: string, groupName: string, leadsCount: number) => void
  /** 업로드 모드만 표시할지 여부 (chatbot에서 사용) */
  uploadOnly?: boolean
}

export function AddLeadSheet({
  open,
  onOpenChange,
  workspaceId,
  customerGroups,
  selectedCustomerGroupId,
  onComplete,
  uploadOnly = false,
}: AddLeadSheetProps) {
  const { t } = useTranslation()
  const queryClient = useQueryClient()

  // Step state
  const [step, setStep] = useState<1 | 2 | 3>(1)
  const [mode, setMode] = useState<"upload" | "manual" | null>(null)
  const [previewLeadData, setPreviewLeadData] = useState<Lead | null>(null)

  // CSV/XLSX upload state
  const [csvData, setCsvData] = useState<LeadCSVData[] | null>(null)
  const [csvFileName, setCsvFileName] = useState("")
  const [csvFileSize, setCsvFileSize] = useState(0)
  const [isProcessingCSV, setIsProcessingCSV] = useState(false)
  const [csvErrors, setCsvErrors] = useState<string[]>([])
  const [isUploadingLeads, setIsUploadingLeads] = useState(false)
  const [isDragging, setIsDragging] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  // Smart CSV parsing state
  const [useSmartParsing] = useState(true) // Always use smart parsing
  const [smartParseResult, setSmartParseResult] = useState<SmartParseResult | null>(null)
  const [showColumnMappingModal, setShowColumnMappingModal] = useState(false)
  const [csvText, setCsvText] = useState<string | null>(null)

  // Group selection state
  const [groupName, setGroupName] = useState("")
  const [groupDescription, setGroupDescription] = useState("")
  const [isNewGroup, setIsNewGroup] = useState(false)
  const [newGroupName, setNewGroupName] = useState("")
  const [isAutoGeneratedGroupName, setIsAutoGeneratedGroupName] = useState(false)
  const [isGeneratingGroupName, setIsGeneratingGroupName] = useState(false)

  // Manual lead creation state
  const [selectedGroupForNewLead, setSelectedGroupForNewLead] = useState("")

  // Generate unique IDs for form elements
  const existingGroupId = useId()
  const newGroupId = useId()
  const groupSelectId = useId()
  const newGroupNameId = useId()
  const groupDescriptionId = useId()

  // Hooks
  const createLead = useCreateLead()
  const createCustomerGroup = useCreateCustomerGroup()

  // Reset state when sheet closes
  useEffect(() => {
    if (!open) {
      setStep(1)
      setMode(null)
      setPreviewLeadData(null)
      setCsvData(null)
      setCsvFileName("")
      setCsvFileSize(0)
      setCsvErrors([])
      setGroupName("")
      setGroupDescription("")
      setIsNewGroup(false)
      setNewGroupName("")
      setCsvText(null)
      setSmartParseResult(null)
    }
  }, [open])

  // Set default group when opening with selectedCustomerGroupId
  useEffect(() => {
    if (open && selectedCustomerGroupId) {
      setGroupName(selectedCustomerGroupId)
      setIsNewGroup(false)
    } else if (open && !selectedCustomerGroupId) {
      setIsNewGroup(true)
    }
  }, [open, selectedCustomerGroupId])

  // Auto-start upload mode if uploadOnly
  useEffect(() => {
    if (open && uploadOnly && step === 1) {
      setMode("upload")
      setStep(2)
    }
  }, [open, uploadOnly, step])

  // Auto-generate group name from CSV data
  const generateGroupNameFromCSV = useCallback(async () => {
    if (!csvData || csvData.length === 0) {
      return
    }

    setIsGeneratingGroupName(true)
    try {
      const template = analyzeCSVLeadsForGroupName(csvData)
      const generatedName = generateGroupName(template)
      setNewGroupName(generatedName)
      setIsAutoGeneratedGroupName(true)
    } catch (error) {
      console.error("Failed to generate group name:", error)
    } finally {
      setIsGeneratingGroupName(false)
    }
  }, [csvData])

  // Auto-generate group name when CSV is loaded and "Create New Group" is selected
  useEffect(() => {
    if (csvData && csvData.length > 0 && isNewGroup) {
      generateGroupNameFromCSV()
    }
  }, [csvData, isNewGroup, generateGroupNameFromCSV])

  // 파일 처리 공통 함수
  const processFile = useCallback(
    async (file: File) => {
      const fileName = file.name.toLowerCase()
      const isCSV = fileName.endsWith(".csv")
      const isXLSX = fileName.endsWith(".xlsx") || fileName.endsWith(".xls")

      if (!(isCSV || isXLSX)) {
        toast.error("CSV 또는 XLSX 파일만 업로드 가능합니다.")
        return
      }

      if (file.size > 10 * 1024 * 1024) {
        toast.error("파일 크기는 10MB를 초과할 수 없습니다.")
        return
      }

      setIsProcessingCSV(true)
      setCsvErrors([])

      try {
        // Smart parsing mode
        if (useSmartParsing) {
          let text: string

          if (isCSV) {
            text = await file.text()
          } else {
            // XLSX → CSV conversion
            const XLSX = await import("xlsx")
            const arrayBuffer = await file.arrayBuffer()
            const workbook = XLSX.read(arrayBuffer, { type: "buffer" })
            const firstSheetName = workbook.SheetNames[0]
            const worksheet = workbook.Sheets[firstSheetName]
            text = XLSX.utils.sheet_to_csv(worksheet)
          }

          setCsvText(text)
          setCsvFileName(file.name)
          setCsvFileSize(file.size)

          // Smart analysis
          const result = smartAnalyzeCSV(text)
          setSmartParseResult(result)

          if (result.errors.length > 0) {
            toast.error(result.errors[0])
            return
          }

          // Show column mapping modal
          setShowColumnMappingModal(true)
          toast.success(`${result.totalRows}개 행이 분석되었습니다. 컬럼 매핑을 확인해주세요.`)
        } else {
          // Legacy parsing mode
          let parsedData: LeadCSVData[]

          if (isCSV) {
            const text = await file.text()
            parsedData = parseCSV(text)
          } else {
            parsedData = await parseXLSX(file)
          }

          const validation = validateCSVData(parsedData)

          if (!validation.valid) {
            setCsvErrors(validation.errors)
            toast.error("파일에 오류가 있습니다.")
            return
          }

          if (validation.warnings.length > 0) {
            validation.warnings.forEach((warning) => {
              console.warn(warning)
            })
          }

          setCsvData(parsedData)
          setCsvFileName(file.name)
          setCsvFileSize(file.size)
          toast.success(`${parsedData.length}개의 리드 데이터를 성공적으로 파싱했습니다.`)
        }
      } catch (error) {
        console.error("파일 파싱 오류:", error)
        const errorMessage =
          error instanceof Error ? error.message : "파일을 읽는 중 오류가 발생했습니다."
        toast.error(errorMessage)
      } finally {
        setIsProcessingCSV(false)
      }
    },
    [useSmartParsing],
  )

  // File upload handler (CSV, XLSX support)
  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file) {
      return
    }
    await processFile(file)
  }

  // 드래그앤드롭 핸들러
  const handleDragEnter = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(true)
  }, [])

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(false)
  }, [])

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
  }, [])

  const handleDrop = useCallback(
    async (e: React.DragEvent) => {
      e.preventDefault()
      e.stopPropagation()
      setIsDragging(false)

      const files = e.dataTransfer.files
      if (files.length > 0) {
        await processFile(files[0])
      }
    },
    [processFile],
  )

  // Smart parsing column mapping confirm handler
  const handleColumnMappingConfirm = useCallback(
    (mappings: Record<string, keyof LeadCSVData | null>, hasHeaders: boolean) => {
      if (!csvText) {
        return
      }

      const { leads, errors } = parseCSVWithMappings(csvText, mappings, hasHeaders)

      if (leads.length === 0) {
        toast.error("유효한 리드 데이터가 없습니다.")
        return
      }

      if (errors.length > 0) {
        console.warn("일부 행 파싱 오류:", errors)
      }

      setCsvData(leads)
      setCsvErrors([])
      setShowColumnMappingModal(false)
      toast.success(`${leads.length}개의 리드가 매핑되었습니다.`)
    },
    [csvText],
  )

  // Header toggle reanalyze handler
  const handleToggleHeaders = useCallback(
    (hasHeaders: boolean) => {
      if (!csvText) {
        return
      }

      const result = smartAnalyzeCSV(csvText, hasHeaders)
      setSmartParseResult(result)

      if (result.errors.length > 0) {
        toast.error(result.errors[0])
      }
    },
    [csvText],
  )

  const handleDownloadTemplate = (format: "csv" | "xlsx") => {
    if (format === "csv") {
      const template = generateCSVTemplate()
      const blob = new Blob([template], { type: "text/csv;charset=utf-8;" })
      const link = document.createElement("a")
      const url = URL.createObjectURL(blob)
      link.setAttribute("href", url)
      link.setAttribute("download", "leads_template.csv")
      link.style.visibility = "hidden"
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    } else {
      const blob = generateXLSXTemplate()
      const link = document.createElement("a")
      const url = URL.createObjectURL(blob)
      link.setAttribute("href", url)
      link.setAttribute("download", "leads_template.xlsx")
      link.style.visibility = "hidden"
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    }
  }

  const handleCSVUpload = async () => {
    if (!csvData || csvData.length === 0) {
      return
    }
    if (!(isNewGroup || groupName)) {
      return
    }

    setIsUploadingLeads(true)
    toast.success(`${csvData.length}개의 리드를 처리 중입니다. 잠시만 기다려주세요...`)

    try {
      let targetGroupId = groupName
      let targetGroupName = ""

      // Create new group if needed
      if (isNewGroup) {
        let finalGroupName = newGroupName.trim()
        if (!finalGroupName) {
          const template = analyzeCSVLeadsForGroupName(csvData)
          finalGroupName = generateGroupName(template)
        }

        const groupData: CreateCustomerGroupRequest = {
          workspaceId,
          name: finalGroupName,
          description: groupDescription || `CSV에서 가져온 ${csvData.length}개의 리드`,
          isDynamic: false,
        }
        const newGroup = await createCustomerGroup.mutateAsync(groupData)
        targetGroupId = newGroup.id
        targetGroupName = finalGroupName
      } else {
        // Find the group name from existing groups
        const existingGroup = customerGroups.find((g) => g.id === groupName)
        targetGroupName = existingGroup?.name || ""
      }

      // Batch processing
      const BATCH_SIZE = 10
      const totalBatches = Math.ceil(csvData.length / BATCH_SIZE)
      const MAX_RETRIES = 2

      let totalCreated = 0
      let totalSkipped = 0
      let errorCount = 0

      for (let i = 0; i < totalBatches; i++) {
        const start = i * BATCH_SIZE
        const end = Math.min(start + BATCH_SIZE, csvData.length)
        const batch = csvData.slice(start, end)

        let batchSuccess = false
        let retryCount = 0

        while (!batchSuccess && retryCount <= MAX_RETRIES) {
          try {
            const response = await leadsApi.createFromCSV({
              workspaceId,
              leads: batch,
              customerGroupId: targetGroupId,
            })

            totalCreated += response.stats.created
            totalSkipped += response.stats.skipped
            batchSuccess = true
          } catch (_error) {
            retryCount++
            if (retryCount <= MAX_RETRIES) {
              await new Promise((resolve) => setTimeout(resolve, 1000 * retryCount))
            } else {
              errorCount += batch.length
            }
          }
        }

        if (i < totalBatches - 1) {
          await new Promise((resolve) => setTimeout(resolve, 500))
        }
      }

      // Invalidate queries
      await queryClient.invalidateQueries({ queryKey: leadKeys.lists() })
      await queryClient.invalidateQueries({ queryKey: customerGroupKeys.all })

      // Show result toast
      if (totalCreated > 0 && totalSkipped > 0) {
        toast.success(
          `${totalCreated}개의 리드가 ${isNewGroup ? "새로 생성된 그룹" : "선택된 그룹"}에 추가되었습니다. (중복 ${totalSkipped}개 스킵)`,
        )
      } else if (totalCreated > 0) {
        toast.success(
          `${totalCreated}개의 리드가 ${isNewGroup ? "새로 생성된 그룹" : "선택된 그룹"}에 성공적으로 추가되었습니다.`,
        )
      } else if (totalSkipped > 0) {
        toast(`모든 리드가 이미 존재하여 스킵되었습니다. (중복 ${totalSkipped}개)`, {
          icon: "⚠️",
          duration: 4000,
        })
      } else if (errorCount > 0) {
        toast.error(`${errorCount}개의 리드 추가에 실패했습니다.`)
      }

      // Call onComplete callback
      if (onComplete && targetGroupId) {
        onComplete(targetGroupId, targetGroupName, totalCreated)
      }

      onOpenChange(false)
    } catch (error) {
      console.error("CSV 업로드 오류:", error)
      let errorMessage = "리드 추가 중 오류가 발생했습니다."
      if (error instanceof Error) {
        errorMessage = `오류: ${error.message}`
      }
      toast.error(errorMessage)
    } finally {
      setIsUploadingLeads(false)
    }
  }

  const handleCreateLead = async (leadData: unknown) => {
    createLead.mutate(leadData as Lead, {
      onSuccess: () => {
        onOpenChange(false)
      },
    })
  }

  return (
    <>
      <Sheet onOpenChange={onOpenChange} open={open}>
        <SheetContent className="overflow-y-auto sm:max-w-2xl">
          <SheetHeader className="fade-in slide-in-from-top-2 animate-in duration-300">
            <SheetTitle>{t("leads.addLead.title")}</SheetTitle>
            <SheetDescription>
              {step === 1 && t("leads.addLead.selectMethod")}
              {step === 2 && mode === "upload" && t("leads.addLead.uploadFile")}
              {step === 2 && mode === "manual" && t("leads.addLead.inputInfo")}
              {step === 3 && t("leads.addLead.checkInfo")}
            </SheetDescription>
          </SheetHeader>

          <div className="mt-6 space-y-6">
            {/* Step 1: Method Selection */}
            {step === 1 && !uploadOnly && (
              <div className="fade-in slide-in-from-bottom-4 animate-in space-y-4 duration-300">
                <div className="grid gap-4">
                  <Card
                    className="fade-in slide-in-from-bottom-2 animate-in cursor-pointer transition-all duration-500 hover:scale-[1.02] hover:border-blue-500 hover:bg-blue-50/50 hover:shadow-md"
                    onClick={() => {
                      setMode("upload")
                      setStep(2)
                    }}
                  >
                    <CardHeader>
                      <div className="flex items-center gap-3">
                        <div className="rounded-lg bg-blue-100 p-2">
                          <Upload className="h-6 w-6 text-blue-600" />
                        </div>
                        <div>
                          <h3 className="font-semibold">{t("leads.addLead.uploadFile")}</h3>
                          <p className="text-muted-foreground text-sm">
                            {t("leads.addLead.uploadFileDescription")}
                          </p>
                        </div>
                      </div>
                    </CardHeader>
                  </Card>

                  <Card
                    className="fade-in slide-in-from-bottom-2 animate-in cursor-pointer transition-all delay-75 duration-500 hover:scale-[1.02] hover:border-blue-500 hover:bg-blue-50/50 hover:shadow-md"
                    onClick={() => {
                      setMode("manual")
                      setStep(2)
                    }}
                  >
                    <CardHeader>
                      <div className="flex items-center gap-3">
                        <div className="rounded-lg bg-blue-100 p-2">
                          <Plus className="h-6 w-6 text-blue-600" />
                        </div>
                        <div>
                          <h3 className="font-semibold">{t("leads.addLead.manualCreate")}</h3>
                          <p className="text-muted-foreground text-sm">
                            {t("leads.addLead.manualCreateDescription")}
                          </p>
                        </div>
                      </div>
                    </CardHeader>
                  </Card>
                </div>
              </div>
            )}

            {/* Step 2: CSV Upload */}
            {step === 2 && mode === "upload" && (
              <div className="fade-in slide-in-from-right-4 animate-in space-y-6 duration-300">
                {/* File Upload Section */}
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <h3 className="font-medium text-lg">{t("leads.file.upload")} (CSV/XLSX)</h3>
                    <div className="flex gap-2">
                      <Button
                        onClick={() => handleDownloadTemplate("csv")}
                        size="sm"
                        type="button"
                        variant="outline"
                      >
                        <Download className="mr-2 h-4 w-4" />
                        {t("leads.button.csvTemplate")}
                      </Button>
                      <Button
                        onClick={() => handleDownloadTemplate("xlsx")}
                        size="sm"
                        type="button"
                        variant="outline"
                      >
                        <Download className="mr-2 h-4 w-4" />
                        {t("leads.button.xlsxTemplate")}
                      </Button>
                    </div>
                  </div>

                  {/* Required Fields Info */}
                  <Card className="border-blue-200 bg-blue-50">
                    <CardContent className="pt-4">
                      <div className="flex items-start gap-3">
                        <div className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-blue-500 font-bold text-sm text-white">
                          !
                        </div>
                        <div className="space-y-2">
                          <h4 className="font-medium text-blue-900">
                            {t("leads.file.requiredFields")}
                          </h4>
                          <div className="text-blue-800 text-sm">
                            <p className="mb-2">
                              <strong>{t("leads.file.requiredFieldsDescription")}</strong>
                            </p>
                            <p className="mb-2">
                              <strong>{t("leads.file.optionalFields")}</strong>
                            </p>
                            <p className="text-blue-600 text-xs">
                              💡 {t("leads.file.templateTip")}
                            </p>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  {csvData ? (
                    <Card>
                      <CardHeader className="pb-3">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <FileText className="h-5 w-5 text-blue-500" />
                            <div>
                              <p className="font-medium">{csvFileName}</p>
                              <p className="text-muted-foreground text-sm">
                                {(csvFileSize / 1024).toFixed(1)} KB
                              </p>
                            </div>
                          </div>
                          <Button
                            onClick={() => {
                              setCsvData(null)
                              setCsvFileName("")
                              setCsvFileSize(0)
                              setCsvErrors([])
                            }}
                            size="sm"
                            variant="outline"
                          >
                            <X className="h-4 w-4" />
                          </Button>
                        </div>
                      </CardHeader>
                      <CardContent>
                        <div className="space-y-4">
                          <div className="flex items-center gap-2">
                            <Badge variant="secondary">
                              {csvData.length}
                              {t("leads.file.leadsCount")}
                            </Badge>
                            <span className="text-muted-foreground text-sm">
                              {t("leads.file.parsingComplete")}
                            </span>
                          </div>

                          {csvErrors.length > 0 && (
                            <Alert>
                              <AlertDescription>
                                <div className="space-y-1">
                                  <p className="font-medium">{t("leads.error.fixErrors")}</p>
                                  <ul className="list-inside list-disc space-y-1">
                                    {csvErrors.map((error) => (
                                      <li className="text-sm" key={error}>
                                        {error}
                                      </li>
                                    ))}
                                  </ul>
                                </div>
                              </AlertDescription>
                            </Alert>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  ) : (
                    <Card>
                      <CardContent className="pt-6">
                        <button
                          className={`w-full rounded-lg border-2 border-dashed p-8 text-center transition-colors ${
                            isDragging
                              ? "border-blue-500 bg-blue-50"
                              : "border-gray-300 hover:border-gray-400"
                          }`}
                          disabled={isProcessingCSV}
                          onClick={() => fileInputRef.current?.click()}
                          onDragEnter={handleDragEnter}
                          onDragLeave={handleDragLeave}
                          onDragOver={handleDragOver}
                          onDrop={handleDrop}
                          type="button"
                        >
                          <Upload
                            className={`mx-auto mb-4 h-12 w-12 ${isDragging ? "text-blue-500" : "text-gray-400"}`}
                          />
                          <div className="space-y-2">
                            <h4 className="font-medium text-lg">
                              {isDragging ? "여기에 파일을 놓으세요" : t("leads.file.upload")}
                            </h4>
                            <p className="text-muted-foreground text-sm">
                              {isDragging
                                ? "CSV 또는 XLSX 파일을 드롭하세요"
                                : "CSV 또는 XLSX 파일을 드래그하거나 클릭하여 업로드하세요"}
                            </p>
                            <div className="pt-4">
                              <input
                                accept=".csv,.xlsx,.xls"
                                className="hidden"
                                onChange={handleFileUpload}
                                ref={fileInputRef}
                                type="file"
                              />
                              <span className="inline-flex h-10 items-center justify-center gap-2 whitespace-nowrap rounded-md bg-primary px-4 py-2 font-medium text-primary-foreground text-sm ring-offset-background transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2">
                                {isProcessingCSV
                                  ? t("leads.button.processing")
                                  : t("leads.button.selectFile")}
                              </span>
                            </div>
                          </div>
                        </button>
                      </CardContent>
                    </Card>
                  )}
                </div>

                {/* Group Info */}
                <div className="space-y-4">
                  <h3 className="font-medium text-lg">{t("leads.group.groupInfo")}</h3>

                  {/* Group Type Selection */}
                  <div className="space-y-3">
                    <div className="flex items-center space-x-4">
                      <div className="flex items-center space-x-2">
                        <input
                          checked={!isNewGroup}
                          className="h-4 w-4 text-blue-600"
                          id={existingGroupId}
                          name="groupType"
                          onChange={() => setIsNewGroup(false)}
                          type="radio"
                        />
                        <Label className="font-medium text-sm" htmlFor={existingGroupId}>
                          {t("leads.group.addToExisting")}
                        </Label>
                      </div>
                      <div className="flex items-center space-x-2">
                        <input
                          checked={isNewGroup}
                          className="h-4 w-4 text-blue-600"
                          id={newGroupId}
                          name="groupType"
                          onChange={() => setIsNewGroup(true)}
                          type="radio"
                        />
                        <Label className="font-medium text-sm" htmlFor={newGroupId}>
                          {t("leads.group.createNew")}
                        </Label>
                      </div>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 gap-4">
                    {isNewGroup ? (
                      <div className="space-y-2">
                        <div className="flex items-center justify-between">
                          <Label htmlFor={newGroupNameId}>{t("leads.group.newGroupName")}</Label>
                          {csvData && csvData.length > 0 && (
                            <div className="flex items-center gap-2">
                              {isAutoGeneratedGroupName && (
                                <Badge className="text-xs" variant="secondary">
                                  {t("leads.addLead.autoGenerated")}
                                </Badge>
                              )}
                              <Button
                                className="h-6 px-2"
                                disabled={isGeneratingGroupName}
                                onClick={generateGroupNameFromCSV}
                                size="sm"
                                title={t("leads.addLead.regenerateGroupName")}
                                type="button"
                                variant="ghost"
                              >
                                <RefreshCw
                                  className={`h-3 w-3 ${isGeneratingGroupName ? "animate-spin" : ""}`}
                                />
                              </Button>
                            </div>
                          )}
                        </div>
                        <Input
                          disabled={isGeneratingGroupName}
                          id={newGroupNameId}
                          onChange={(e) => {
                            setNewGroupName(e.target.value)
                            setIsAutoGeneratedGroupName(false)
                          }}
                          placeholder={
                            isGeneratingGroupName
                              ? "그룹명 생성 중..."
                              : t("leads.group.newGroupNamePlaceholder")
                          }
                          value={newGroupName}
                        />
                        {isAutoGeneratedGroupName && (
                          <p className="text-muted-foreground text-xs">
                            {t("leads.addLead.autoGeneratedDescription")}
                          </p>
                        )}
                      </div>
                    ) : (
                      <div className="space-y-2">
                        <Label htmlFor={groupSelectId}>{t("leads.group.selectGroup")}</Label>
                        <Select onValueChange={setGroupName} value={groupName}>
                          <SelectTrigger id={groupSelectId}>
                            <SelectValue placeholder={t("leads.group.selectGroupPlaceholder")} />
                          </SelectTrigger>
                          <SelectContent>
                            {customerGroups?.map((group) => (
                              <SelectItem key={group.id} value={group.id}>
                                {group.name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                    )}

                    <div className="space-y-2">
                      <Label htmlFor={groupDescriptionId}>
                        {t("leads.group.groupDescription")}
                      </Label>
                      <Input
                        id={groupDescriptionId}
                        onChange={(e) => setGroupDescription(e.target.value)}
                        placeholder={t("leads.group.groupDescriptionPlaceholder")}
                        value={groupDescription}
                      />
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Step 2: Manual Creation */}
            {step === 2 && mode === "manual" && (
              <div className="fade-in slide-in-from-right-4 animate-in space-y-4 duration-300">
                <LeadForm
                  cancelButtonText="이전"
                  customerGroups={customerGroups}
                  isEdit={false}
                  onCancel={() => {
                    setStep(1)
                    setMode(null)
                  }}
                  onGroupChange={(value) =>
                    setSelectedGroupForNewLead(value === "none" ? "" : value)
                  }
                  onSave={(leadData) => {
                    setPreviewLeadData(leadData as Lead)
                    setStep(3)
                  }}
                  selectedGroup={selectedGroupForNewLead}
                  submitButtonText="다음"
                  workspaceId={workspaceId}
                />
              </div>
            )}

            {/* Step 3: Preview */}
            {step === 3 && (
              <div className="fade-in slide-in-from-right-4 animate-in space-y-4 duration-300">
                {mode === "upload" && csvData ? (
                  <div className="space-y-4">
                    <h3 className="font-medium text-lg">{t("leads.addLead.preview")}</h3>
                    <Card>
                      <CardContent className="pt-4">
                        <div className="space-y-4">
                          <div className="flex items-center justify-between">
                            <div>
                              <p className="font-medium">
                                {t("leads.addLead.totalLeads", { count: csvData.length })}
                              </p>
                              <p className="text-muted-foreground text-sm">
                                {isNewGroup
                                  ? t("leads.addLead.addToNewGroup", {
                                      name: newGroupName || t("leads.addLead.autoGenerated"),
                                    })
                                  : t("leads.addLead.addToExistingGroup")}
                              </p>
                            </div>
                          </div>

                          <div className="max-h-96 space-y-2 overflow-y-auto">
                            {csvData.slice(0, 10).map((lead, index) => (
                              <div
                                className="fade-in slide-in-from-left-2 animate-in rounded-lg bg-gray-50 p-3 text-sm duration-300"
                                key={`${lead.companyName}-${lead.primaryEmail}-${index}`}
                                style={{ animationDelay: `${index * 50}ms` }}
                              >
                                <div className="font-medium">{lead.companyName}</div>
                                <div className="text-muted-foreground text-xs">
                                  {lead.primaryEmail || t("leads.file.noEmail")} •{" "}
                                  {lead.contactName || t("leads.file.noName")}
                                </div>
                              </div>
                            ))}
                            {csvData.length > 10 && (
                              <p className="fade-in animate-in py-2 text-center text-muted-foreground text-sm delay-500 duration-300">
                                ... 외 {csvData.length - 10}개
                              </p>
                            )}
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  </div>
                ) : (
                  previewLeadData && (
                    <div className="space-y-4">
                      <h3 className="fade-in animate-in font-medium text-lg duration-300">
                        추가할 리드 정보
                      </h3>
                      <Card className="fade-in slide-in-from-bottom-2 animate-in duration-500">
                        <CardContent className="space-y-4 pt-4">
                          {/* Basic Info */}
                          <div>
                            <h4 className="mb-2 font-semibold text-blue-600 text-sm">기본 정보</h4>
                            <div className="grid grid-cols-2 gap-3 text-sm">
                              <div className="space-y-1">
                                <span className="text-muted-foreground">회사명</span>
                                <p className="font-medium">{previewLeadData.companyName || "-"}</p>
                              </div>
                              <div className="space-y-1">
                                <span className="text-muted-foreground">담당자</span>
                                <p className="font-medium">{previewLeadData.contactName || "-"}</p>
                              </div>
                              <div className="space-y-1">
                                <span className="text-muted-foreground">웹사이트</span>
                                <p className="break-all font-medium">
                                  {previewLeadData.websiteUrl || "-"}
                                </p>
                              </div>
                              <div className="space-y-1">
                                <span className="text-muted-foreground">업종</span>
                                <p className="font-medium">{previewLeadData.businessType || "-"}</p>
                              </div>
                            </div>
                          </div>

                          {/* Location Info */}
                          {(previewLeadData.country ||
                            previewLeadData.city ||
                            previewLeadData.address) && (
                            <div className="border-t pt-4">
                              <h4 className="mb-2 font-semibold text-blue-600 text-sm">
                                위치 정보
                              </h4>
                              <div className="grid grid-cols-2 gap-3 text-sm">
                                {previewLeadData.country && (
                                  <div className="space-y-1">
                                    <span className="text-muted-foreground">국가</span>
                                    <p className="font-medium">{previewLeadData.country}</p>
                                  </div>
                                )}
                                {previewLeadData.city && (
                                  <div className="space-y-1">
                                    <span className="text-muted-foreground">도시</span>
                                    <p className="font-medium">{previewLeadData.city}</p>
                                  </div>
                                )}
                                {previewLeadData.address && (
                                  <div className="col-span-2 space-y-1">
                                    <span className="text-muted-foreground">주소</span>
                                    <p className="font-medium">{previewLeadData.address}</p>
                                  </div>
                                )}
                              </div>
                            </div>
                          )}

                          {/* Contacts */}
                          {previewLeadData.contacts && previewLeadData.contacts.length > 0 && (
                            <div className="border-t pt-4">
                              <h4 className="mb-2 font-semibold text-blue-600 text-sm">
                                연락처 정보
                              </h4>
                              <div className="space-y-2">
                                {previewLeadData.contacts.map((contact, index) => (
                                  <div
                                    className="flex items-center gap-2 rounded bg-gray-50 p-2 text-sm"
                                    key={`${contact.contactType}-${contact.contactValue}-${index}`}
                                  >
                                    <Badge className="text-xs" variant="outline">
                                      {contact.contactType}
                                    </Badge>
                                    <span className="font-medium">{contact.contactValue}</span>
                                    {contact.contactName && (
                                      <span className="text-muted-foreground">
                                        ({contact.contactName})
                                      </span>
                                    )}
                                    {contact.isPrimary && (
                                      <Badge className="text-xs" variant="secondary">
                                        주 연락처
                                      </Badge>
                                    )}
                                  </div>
                                ))}
                              </div>
                            </div>
                          )}

                          {/* Social Media */}
                          {previewLeadData.socialMedia &&
                            previewLeadData.socialMedia.length > 0 && (
                              <div className="border-t pt-4">
                                <h4 className="mb-2 font-semibold text-blue-600 text-sm">
                                  소셜 미디어
                                </h4>
                                <div className="space-y-2">
                                  {previewLeadData.socialMedia.map((social, index) => (
                                    <div
                                      className="flex items-center gap-2 rounded bg-gray-50 p-2 text-sm"
                                      key={`${social.platform}-${social.url}-${index}`}
                                    >
                                      <Badge className="text-xs" variant="outline">
                                        {social.platform}
                                      </Badge>
                                      <span className="break-all font-medium">{social.url}</span>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            )}

                          {/* Additional Info */}
                          {(previewLeadData.description || previewLeadData.notes) && (
                            <div className="border-t pt-4">
                              <h4 className="mb-2 font-semibold text-blue-600 text-sm">
                                추가 정보
                              </h4>
                              {previewLeadData.description && (
                                <div className="mb-3 space-y-1">
                                  <span className="text-muted-foreground text-sm">설명</span>
                                  <p className="rounded bg-gray-50 p-2 text-sm">
                                    {previewLeadData.description}
                                  </p>
                                </div>
                              )}
                              {previewLeadData.notes && (
                                <div className="space-y-1">
                                  <span className="text-muted-foreground text-sm">메모</span>
                                  <p className="rounded bg-gray-50 p-2 text-sm">
                                    {previewLeadData.notes}
                                  </p>
                                </div>
                              )}
                            </div>
                          )}
                        </CardContent>
                      </Card>
                    </div>
                  )
                )}
              </div>
            )}
          </div>

          <SheetFooter className="fade-in slide-in-from-bottom-2 mt-6 animate-in delay-150 duration-300">
            {step === 1 && !uploadOnly && (
              <Button
                className="transition-all duration-200 hover:scale-105 active:scale-95"
                onClick={() => onOpenChange(false)}
                variant="outline"
              >
                취소
              </Button>
            )}

            {step === 2 && (
              <>
                <Button
                  className="transition-all duration-200 hover:scale-105 active:scale-95"
                  onClick={() => {
                    if (uploadOnly) {
                      onOpenChange(false)
                    } else {
                      setStep(1)
                      setMode(null)
                      setCsvData(null)
                    }
                  }}
                  variant="outline"
                >
                  {uploadOnly ? "취소" : "이전"}
                </Button>
                {mode === "upload" && (
                  <Button
                    className="transition-all duration-200 hover:scale-105 active:scale-95"
                    disabled={
                      !csvData ||
                      csvErrors.length > 0 ||
                      !(isNewGroup || groupName) ||
                      (isNewGroup && !newGroupName.trim())
                    }
                    onClick={() => {
                      if (csvData && csvData.length > 0) {
                        setStep(3)
                      }
                    }}
                  >
                    다음
                  </Button>
                )}
              </>
            )}

            {step === 3 && (
              <>
                <Button
                  className="transition-all duration-200 hover:scale-105 active:scale-95"
                  onClick={() => {
                    setStep(2)
                    setPreviewLeadData(null)
                  }}
                  variant="outline"
                >
                  이전
                </Button>
                <Button
                  className="transition-all duration-200 hover:scale-105 active:scale-95"
                  disabled={isUploadingLeads || createLead.isPending}
                  onClick={async () => {
                    if (mode === "upload") {
                      await handleCSVUpload()
                    } else if (previewLeadData) {
                      await handleCreateLead(previewLeadData)
                    }
                  }}
                >
                  {isUploadingLeads || createLead.isPending ? "처리 중..." : "리드 추가"}
                </Button>
              </>
            )}
          </SheetFooter>
        </SheetContent>
      </Sheet>

      {/* Column Mapping Modal */}
      <ColumnMappingModal
        isOpen={showColumnMappingModal}
        onClose={() => {
          setShowColumnMappingModal(false)
          setSmartParseResult(null)
          setCsvText(null)
        }}
        onConfirm={handleColumnMappingConfirm}
        onToggleHeaders={handleToggleHeaders}
        parseResult={smartParseResult}
      />
    </>
  )
}
