#!/bin/sh

# Change to admin directory and run biome check with yarn
cd admin && yarn run check

# Change to elysia-server directory and run biome check with bun
cd ../elysia-server && bun run lint:check